'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { knowledgeTargetKind, type KnowledgeValue } from '@nextdoo/contracts';
import { renderDescription } from '@nextdoo/core/description';
import { api, type Task } from '@/lib/api';
import { TaskAttachments } from '@/components/TaskAttachments';
import { TaskEditor } from '@/components/TaskEditor';
import { RecordForm } from './KnowledgeDatabase';
import { KnowledgeHeader, KnowledgeStatus, KnowledgePager, KnowledgeBacklinks, useKnowledgeRead, useKnowledgeCommand, displayValue, errorMessage, type Property, type KnowledgeDatabase, type KnowledgeItem, type Page } from './shared';
interface Relation {id:string;propertyId:string|null;kind:string;targetId:string;target:{label:string;href:string|null;unavailable:boolean};}
interface Detail {record:KnowledgeItem;database:KnowledgeDatabase;properties:Property[];values:Record<string,KnowledgeValue>;relations:{data:Relation[]};notes:Page<KnowledgeItem>;files:Array<{id:string;propertyId:string;fileName:string;scanStatus:string;deletedAt:string|null}>;}
interface NoteDetail {note:KnowledgeItem;tags:Array<{id:string;name:string}>;relations:{data:Relation[]};}

export function KnowledgeRecordView({id}:{id:string}) {
  const read=useKnowledgeRead<Detail>(`/knowledge/records/${id}`),command=useKnowledgeCommand(),router=useRouter();const [editing,setEditing]=useState(false),[reload,setReload]=useState(0);
  const detail=read.data,record=detail?.record;
  const refresh=()=>{setEditing(false);read.refresh();};
  return <div className="knowledge-view"><KnowledgeHeader/><KnowledgeStatus loading={read.loading} error={read.error||command.error}/>{detail&&record&&<><Link href={`/knowledge/databases/${record.databaseId}`}>{detail.database.name}</Link><h1>{record.title}</h1><p className="muted">Updated {new Date(record.updatedAt).toLocaleString()}{record.deletedAt?' · Deleted':''}</p><div className="row"><button onClick={()=>{read.refresh();setReload(v=>v+1);}}>Reload saved version</button><button disabled={!!record.deletedAt||detail.database.archived} onClick={()=>setEditing(v=>!v)}>{editing?'Close editor':'Edit record'}</button><button disabled={command.busy||editing||detail.database.archived} onClick={async()=>{if(await command.send(`/knowledge/records/${id}${record.deletedAt?'/restore':''}`,{version:record.version},record.deletedAt?'POST':'DELETE'))refresh();}}>{record.deletedAt?'Restore record':'Delete record'}</button><button disabled={command.busy||editing||!!record.deletedAt||detail.database.archived} onClick={async()=>{const copy=await command.send<{id:string}>(`/knowledge/records/${id}/duplicate`,{version:record.version});if(copy)router.push(`/knowledge/records/${copy.id}`);}}>Duplicate record</button></div>
    {editing?<RecordForm key={`${record.version}-${reload}`} properties={detail.properties} path={`/knowledge/records/${id}`} initial={{...record,values:detail.values}} onSaved={refresh}/>:<section className="card"><dl>{detail.properties.filter(p=>!['TITLE','FILE','RELATION'].includes(p.type)).map(p=><div key={p.id}><dt>{p.name}</dt><dd>{p.type==='RICH_TEXT'?<div className="description-content" dangerouslySetInnerHTML={{__html:renderDescription(String(detail.values[p.id]??''))}}/>:displayValue(detail.values[p.id])}</dd></div>)}</dl><div className="description-content" dangerouslySetInnerHTML={{__html:renderDescription(record.content)}}/></section>}
    {!record.deletedAt&&<><KnowledgeRelations source="records" item={record} properties={detail.properties} links={detail.relations.data} disabled={editing||detail.database.archived} onSaved={refresh}/><FileProperties item={record} properties={detail.properties} files={detail.files} disabled={editing||detail.database.archived} onSaved={refresh}/><section className="card"><TaskAttachments recordId={id} disabled={editing||detail.database.archived}/></section><section className="card"><h2>Record notes</h2><Link href={`/knowledge/notes/new?recordId=${id}`}>Add record note</Link><ul>{detail.notes.data.map(n=><li key={n.id}><Link href={`/knowledge/notes/${n.id}`}>{n.title}</Link></li>)}</ul>{detail.notes.nextOffset!==null&&<Link href={`/knowledge/notes?recordId=${id}`}>Browse all record notes</Link>}</section></>}
    <KnowledgeBacklinks kind="record" id={id}/>
  </>}</div>;
}
export function KnowledgeNoteView({id,recordId,databaseId}:{id:string;recordId?:string;databaseId?:string}) {
  if(id==='new')return <div className="knowledge-view"><KnowledgeHeader/><h1>New note</h1><NoteForm recordId={recordId} databaseId={databaseId}/></div>;
  return <SavedNote id={id}/>;
}
function SavedNote({id}:{id:string}) {
  const read=useKnowledgeRead<NoteDetail>(`/knowledge/notes/${id}`),command=useKnowledgeCommand();const [editing,setEditing]=useState(false),[reload,setReload]=useState(0);const note=read.data?.note;
  const refresh=()=>{setEditing(false);read.refresh();};
  return <div className="knowledge-view"><KnowledgeHeader/><KnowledgeStatus loading={read.loading} error={read.error||command.error}/>{note&&read.data&&<><h1>{note.title}</h1>{note.recordId&&<Link href={`/knowledge/records/${note.recordId}`}>Parent record</Link>}{note.databaseId&&<Link href={`/knowledge/databases/${note.databaseId}`}>Parent database</Link>}<div className="row"><button onClick={()=>{read.refresh();setReload(v=>v+1);}}>Reload saved version</button><button disabled={!!note.deletedAt} onClick={()=>setEditing(v=>!v)}>{editing?'Close editor':'Edit note'}</button><button disabled={editing||command.busy} onClick={async()=>{if(await command.send(`/knowledge/notes/${id}${note.deletedAt?'/restore':''}`,{version:note.version},note.deletedAt?'POST':'DELETE'))refresh();}}>{note.deletedAt?'Restore note':'Delete note'}</button></div>
    {editing?<NoteForm key={`${note.version}-${reload}`} initial={read.data} onSaved={refresh}/>:<section className="card"><p className="muted">{read.data.tags.map(t=>t.name).join(' · ')}</p><div className="description-content" dangerouslySetInnerHTML={{__html:renderDescription(note.content)}}/></section>}
    {!note.deletedAt&&<><KnowledgeRelations source="notes" item={note} properties={[]} links={read.data.relations.data} disabled={editing} onSaved={refresh}/><section className="card"><TaskAttachments noteId={id} disabled={editing}/></section></>}<KnowledgeBacklinks kind="note" id={id}/>
  </>}</div>;
}
function NoteForm({initial,recordId,databaseId,onSaved}:{initial?:NoteDetail;recordId?:string;databaseId?:string;onSaved?:()=>void}) {
  const [title,setTitle]=useState(initial?.note.title??''),[content,setContent]=useState(initial?.note.content??''),[tagIds,setTagIds]=useState(initial?.tags.map(t=>t.id)??[]),[preview,setPreview]=useState(false);
  const tags=useKnowledgeRead<Page<{id:string;name:string}>>('/tags'),command=useKnowledgeCommand(),router=useRouter();
  return <form className="card knowledge-form" aria-label={initial?'Edit note':'New note'} onSubmit={async e=>{e.preventDefault();const result=await command.send<{id:string}>(`/knowledge/notes${initial?'/'+initial.note.id:''}`,{title,content,tagIds,...(initial?{version:initial.note.version}:{recordId:recordId??null,databaseId:databaseId??null})},initial?'PATCH':'POST');if(result){if(onSaved)onSaved();else router.push(`/knowledge/notes/${result.id}`);}}}><fieldset disabled={command.busy}><legend>{initial?'Edit note':'New note'}</legend><label>Note title<input required maxLength={500} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Note content (Markdown)<textarea rows={12} maxLength={20000} value={content} onChange={e=>setContent(e.target.value)}/></label><button type="button" onClick={()=>setPreview(v=>!v)}>Preview content</button>{preview&&<div className="description-content" dangerouslySetInnerHTML={{__html:renderDescription(content)}}/>}<fieldset><legend>Tags</legend>{tags.data?.data.map(t=><label key={t.id} className="row"><input type="checkbox" checked={tagIds.includes(t.id)} onChange={e=>setTagIds(old=>e.target.checked?[...old,t.id]:old.filter(id=>id!==t.id))}/>{t.name}</label>)}{tags.data?.data.length===0&&<p className="muted">No workspace tags yet. Existing task tags can also label notes.</p>}</fieldset><button>{initial?'Save note':'Create note'}</button></fieldset><KnowledgeStatus error={command.error||tags.error}/></form>;
}
function KnowledgeRelations({source,item,properties,links,disabled,onSaved}:{source:'records'|'notes';item:KnowledgeItem;properties:Property[];links:Relation[];disabled:boolean;onSaved:()=>void}) {
  const [propertyId,setPropertyId]=useState(''),[kind,setKind]=useState('record'),[search,setSearch]=useState(''),[q,setQ]=useState(''),[offset,setOffset]=useState(0),[task,setTask]=useState<Task|null>(null),[error,setError]=useState('');const property=properties.find(p=>p.id===propertyId);
  const targetKind=property?.config.relationKind??kind;
  const targets=useKnowledgeRead<Page<{id:string;label:string}>>(`/knowledge/targets?kind=${targetKind}&q=${encodeURIComponent(q)}&offset=${offset}${property?.config.relationDatabaseId?'&databaseId='+property.config.relationDatabaseId:''}`),command=useKnowledgeCommand();
  async function link(targetId:string,linked:boolean,k=targetKind,p:string|null=propertyId||null){if(await command.send(`/knowledge/${source}/${item.id}/relations`,{version:item.version,kind:k,targetId,propertyId:p,linked}))onSaved();}
  return <section className="card" aria-label="Relations"><h2>Relations</h2><KnowledgeStatus error={command.error||targets.error||error}/><ul>{links.map(l=><li key={l.id}><span>{l.propertyId?properties.find(p=>p.id===l.propertyId)?.name+': ':''}{l.kind} · </span>{l.target.href?<Link href={l.target.href}>{l.target.label}</Link>:l.kind==='task'&&!l.target.unavailable?<button type="button" onClick={async()=>{try{setTask(await api<Task>(`/tasks/${l.targetId}`));}catch(e){setError(errorMessage(e));}}}>{l.target.label}</button>:l.target.label} <button disabled={disabled||command.busy} onClick={()=>void link(l.targetId,false,l.kind,l.propertyId)}>Unlink {l.target.label}</button></li>)}</ul>
    <form className="knowledge-form" onSubmit={e=>{e.preventDefault();setQ(search);setOffset(0);}}><fieldset disabled={disabled||command.busy}><legend>Add a relation</legend>{properties.some(p=>p.type==='RELATION')&&<label>Relation property<select value={propertyId} onChange={e=>{setPropertyId(e.target.value);setOffset(0);}}><option value="">General relation</option>{properties.filter(p=>p.type==='RELATION').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}<label>Item type<select disabled={!!property} value={targetKind} onChange={e=>{setKind(e.target.value);setOffset(0);}}>{knowledgeTargetKind.options.map(k=><option key={k}>{k}</option>)}</select></label><label>Find an item<input maxLength={200} value={search} onChange={e=>setSearch(e.target.value)}/></label><button>Search items</button></fieldset></form><KnowledgeStatus loading={targets.loading}/><ul>{targets.data?.data.filter(t=>t.id!==item.id).map(t=><li key={t.id}>{t.label} <button disabled={disabled||command.busy||links.some(l=>l.targetId===t.id&&l.propertyId===(propertyId||null)&&l.kind===targetKind)} onClick={()=>void link(t.id,true)}>Link {t.label}</button></li>)}</ul>{targets.data&&<KnowledgePager offset={offset} nextOffset={targets.data.nextOffset} setOffset={setOffset}/>}{task&&<TaskEditor task={task} onClose={()=>setTask(null)} onSaved={onSaved}/>}
  </section>;
}
function FileProperties({item,properties,files,disabled,onSaved}:{item:KnowledgeItem;properties:Property[];files:Detail['files'];disabled:boolean;onSaved:()=>void}) {
  const definitions=properties.filter(p=>p.type==='FILE');const [propertyId,setPropertyId]=useState(definitions[0]?.id??''),[q,setQ]=useState(''),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[error,setError]=useState('');const command=useKnowledgeCommand();
  const resources=useKnowledgeRead<Page<{id:string;fileName:string}>>(`/knowledge/resources?q=${encodeURIComponent(q)}&offset=${offset}`);
  if(!definitions.length)return null;
  async function link(attachmentId:string,linked:boolean,p=propertyId){if(await command.send(`/knowledge/records/${item.id}/files`,{version:item.version,propertyId:p,attachmentId,linked}))onSaved();}
  return <section className="card"><h2>File properties</h2><p>Upload below, then refresh this search after the scan finishes to reference the file. You can also reuse files attached to your tasks, goals and notes.</p><KnowledgeStatus error={command.error||resources.error||error}/><ul>{files.map(f=><li key={f.id+f.propertyId}>{properties.find(p=>p.id===f.propertyId)?.name}: {f.fileName} <button disabled={!!f.deletedAt||f.scanStatus!=='CLEAN'} onClick={async()=>{try{const r=await api<{downloadUrl:string}>(`/attachments/${f.id}/download`);window.location.assign(r.downloadUrl);}catch(e){setError(errorMessage(e));}}}>Download {f.fileName}</button><button disabled={disabled||command.busy} onClick={()=>void link(f.id,false,f.propertyId)}>Unlink file</button></li>)}</ul><form className="knowledge-form" onSubmit={e=>{e.preventDefault();setQ(search);setOffset(0);resources.refresh();}}><label>File property<select value={propertyId} onChange={e=>setPropertyId(e.target.value)}>{definitions.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Find a file<input maxLength={200} value={search} onChange={e=>setSearch(e.target.value)}/></label><button>Search files</button></form><ul>{resources.data?.data.map(f=><li key={f.id}>{f.fileName} <button disabled={disabled||command.busy||files.some(v=>v.id===f.id&&v.propertyId===propertyId)} onClick={()=>void link(f.id,true)}>Use {f.fileName}</button></li>)}</ul>{resources.data&&<KnowledgePager offset={offset} nextOffset={resources.data.nextOffset} setOffset={setOffset}/>}</section>;
}
