'use client';
import Link from 'next/link';
import { useState } from 'react';
import { KNOWLEDGE_TYPES, knowledgeTargetKind, type KnowledgeValue, type KnowledgePropertyInput } from '@nextdoo/contracts';
import { api } from '@/lib/api';
import { KnowledgeHeader, KnowledgePager, KnowledgeStatus, useKnowledgeRead, useKnowledgeCommand, ValueInput, displayValue, errorMessage, type KnowledgeDatabase, type Property, type RecordRow, type Page } from './shared';

interface DatabasePage extends Page<RecordRow>{database:KnowledgeDatabase;properties:Property[];total:number;}
export function KnowledgeDatabaseView({id}:{id:string}) {
  const [offset,setOffset]=useState(0),[query,setQuery]=useState(''),[q,setQ]=useState(''),[sort,setSort]=useState('updatedAt'),[direction,setDirection]=useState('desc'),[deleted,setDeleted]=useState(false);
  const [filterId,setFilterId]=useState(''),[operator,setOperator]=useState('eq'),[filterValue,setFilterValue]=useState<KnowledgeValue>(null),[filters,setFilters]=useState('[]');
  const [view,setView]=useState('table'),[newRecord,setNewRecord]=useState(false),[error,setError]=useState('');
  const params=new URLSearchParams({q:query,sort,direction,includeDeleted:String(deleted),offset:String(offset),filters});
  const read=useKnowledgeRead<DatabasePage>(`/knowledge/databases/${id}?${params}`),command=useKnowledgeCommand();const page=read.data;
  const selected=page?.properties.find(p=>p.id===filterId),visible=page?.properties.filter(p=>!p.hidden)??[];
  async function exportPage(format:'csv'|'json') {try {const result=await api<{content:string}>(`/knowledge/databases/${id}/export?${params}&format=${format}`);const url=URL.createObjectURL(new Blob([result.content],{type:format==='csv'?'text/csv;charset=utf-8':'application/json'}));const a=document.createElement('a');a.href=url;a.download=`knowledge-page-${Math.floor(offset/40)+1}.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(errorMessage(e));}}
  const cell=(row:RecordRow,p:Property)=>p.type==='TITLE'?<Link href={`/knowledge/records/${row.id}`}>{row.title}{row.deletedAt?' (deleted)':''}</Link>:['FILE','RELATION'].includes(p.type)?`${row.referenceCounts[p.id]??0} references`:displayValue(row.values[p.id]);
  return <div className="knowledge-view"><KnowledgeHeader/><KnowledgeStatus error={read.error||error||command.error} loading={read.loading}/>{page&&<><h1>{page.database.icon} {page.database.name}</h1><p>{page.database.description}</p><div className="row"><button disabled={command.busy} onClick={async()=>{if(await command.send(`/knowledge/databases/${id}`,{version:page.database.version,favorite:!page.database.favorite},'PATCH'))read.refresh();}}>{page.database.favorite?'Unfavorite':'Favorite'}</button><button disabled={page.database.archived} onClick={()=>setNewRecord(v=>!v)}>New record</button><Link href={`/knowledge/notes/new?databaseId=${id}`}>Add database note</Link><button onClick={()=>void exportPage('csv')}>Export this page as CSV</button><button onClick={()=>void exportPage('json')}>Export this page as JSON</button></div>
    {page.database.archived&&<p role="status">This database is archived. Restore it in settings to edit records.</p>}
    <details><summary>Database settings and properties</summary><DatabaseSettings key={page.database.version} database={page.database} onSaved={read.refresh}/><Properties key={`properties-${page.database.version}`} database={page.database} properties={page.properties} onSaved={read.refresh}/></details>
    {newRecord&&!page.database.archived&&<RecordForm properties={page.properties} path={`/knowledge/databases/${id}/records`} onSaved={()=>{setNewRecord(false);read.refresh();}}/>}
    <form className="card knowledge-form" aria-label="Record filters" onSubmit={e=>{e.preventDefault();setQuery(q);setFilters(filterId?JSON.stringify([{propertyId:filterId,operator,...(!['exists','missing'].includes(operator)?{value:filterValue}:{})}]):'[]');setOffset(0);}}>
      <div className="knowledge-grid"><label>Search records<input maxLength={200} value={q} onChange={e=>setQ(e.target.value)}/></label><label>Filter property<select value={filterId} onChange={e=>{setFilterId(e.target.value);setFilterValue(null);}}><option value="">All records</option>{page.properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{selected&&<><label>Filter condition<select value={operator} onChange={e=>setOperator(e.target.value)}>{(['eq','contains','exists','missing','gt','gte','lt','lte']).map(op=><option key={op} value={op}>{{eq:'Equals',contains:'Contains',exists:'Has a value',missing:'Missing',gt:'Greater than / after',gte:'At least / on or after',lt:'Less than / before',lte:'At most / on or before'}[op]}</option>)}</select></label>{!['exists','missing'].includes(operator)&&<ValueInput property={{...selected,name:'Filter value',...(selected.type==='MULTI_SELECT'&&operator==='contains'?{type:'SELECT'}:{})}} value={filterValue} onChange={setFilterValue}/>}</>}</div>
      <button>Apply filters</button><button type="button" onClick={()=>{setFilterId('');setFilters('[]');setQ('');setQuery('');setOffset(0);}}>Clear filters</button>
    </form>
    <div className="row"><label>Sort by<select value={sort} onChange={e=>{setSort(e.target.value);setOffset(0);}}><option value="updatedAt">Updated</option><option value="createdAt">Created</option>{page.properties.filter(p=>!['FILE','RELATION','RICH_TEXT','MULTI_SELECT'].includes(p.type)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Direction<select aria-label="Direction" value={direction} onChange={e=>{setDirection(e.target.value);setOffset(0);}}><option value="asc">Ascending</option><option value="desc">Descending</option></select></label><label><input type="checkbox" checked={deleted} onChange={e=>{setDeleted(e.target.checked);setOffset(0);}}/>Include deleted records</label><label>View<select aria-label="View" value={view} onChange={e=>setView(e.target.value)}><option value="table">Table</option><option value="list">List</option><option value="gallery">Gallery</option><option value="board">Board</option></select></label></div>
    <p>{page.total} matching records · Showing {page.data.length} on this page. Views and exports use this page.</p>
    {!page.data.length&&<p>No matching records. Add a record or adjust the filters.</p>}
    {view==='table'?<div className="tracker-table-wrap" tabIndex={0} role="region" aria-label="Records table"><table><thead><tr>{visible.map(p=><th key={p.id} scope="col">{p.name}</th>)}</tr></thead><tbody>{page.data.map(row=><tr key={row.id}>{visible.map(p=><td key={p.id}>{cell(row,p)}</td>)}</tr>)}</tbody></table></div>:view==='board'?<div className="board-columns">{(()=>{const p=page.properties.find(p=>p.type==='SELECT');return [...(p?.config.options??[]),'Not set'].map(option=><section className="card" key={option}><h2>{option}</h2>{page.data.filter(row=>(p?row.values[p.id]??'Not set':'Not set')===option).map(row=><p key={row.id}><Link href={`/knowledge/records/${row.id}`}>{row.title}</Link></p>)}</section>);})()}</div>:<div className={view==='gallery'?'knowledge-grid':''}>{page.data.map(row=><article className="card" key={row.id}><h2><Link href={`/knowledge/records/${row.id}`}>{row.title}</Link></h2>{visible.filter(p=>p.type!=='TITLE').map(p=><p key={p.id}><strong>{p.name}: </strong>{cell(row,p)}</p>)}</article>)}</div>}
    <KnowledgePager offset={offset} nextOffset={page.nextOffset} setOffset={setOffset}/><p><Link href={`/knowledge/notes?databaseId=${id}`}>Browse database notes</Link></p><p className="muted">For a complete structured export, use Account settings → Export account data. Board groups by the first Select property.</p>
  </>}</div>;
}
function DatabaseSettings({database,onSaved}:{database:KnowledgeDatabase;onSaved:()=>void}) {
  const [name,setName]=useState(database.name),[description,setDescription]=useState(database.description??''),[icon,setIcon]=useState(database.icon??''),[color,setColor]=useState(database.color??'#6366f1');const command=useKnowledgeCommand();
  return <form className="card knowledge-form" aria-label="Database settings" onSubmit={async e=>{e.preventDefault();if(await command.send(`/knowledge/databases/${database.id}`,{version:database.version,name,description,icon:icon||null,color},'PATCH'))onSaved();}}><label>Name<input required maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label><label>Description<textarea maxLength={10000} value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Icon<input maxLength={8} value={icon} onChange={e=>setIcon(e.target.value)}/></label><label>Color<input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><KnowledgeStatus error={command.error}/><button disabled={command.busy}>Save settings</button><button type="button" disabled={command.busy} onClick={async()=>{if(await command.send(`/knowledge/databases/${database.id}`,{version:database.version,archived:!database.archived},'PATCH'))onSaved();}}>{database.archived?'Restore database':'Archive database'}</button></form>;
}
function Properties({database,properties,onSaved}:{database:KnowledgeDatabase;properties:Property[];onSaved:()=>void}) {
  const [edit,setEdit]=useState<Property|null>(null),[name,setName]=useState(''),[type,setType]=useState<KnowledgePropertyInput['type']>('TEXT'),[options,setOptions]=useState(''),[hidden,setHidden]=useState(false),[kind,setKind]=useState<KnowledgePropertyInput['config']['relationKind']>('record'),[related,setRelated]=useState('');
  const command=useKnowledgeCommand(),databases=useKnowledgeRead<Page<KnowledgeDatabase>>('/knowledge/databases?limit=100');
  function choose(p:Property){setEdit(p);setName(p.name);setType(p.type);setOptions(p.config.options.join('\n'));setHidden(p.hidden);setKind(p.config.relationKind);setRelated(p.config.relationDatabaseId??'');}
  return <section className="card"><h2>Properties</h2><p>Types stay fixed to protect stored data. Only empty properties can be removed. Hidden properties remain available in record details.</p><KnowledgeStatus error={command.error}/><ol>{properties.map((p,i)=><li key={p.id}><span>{p.name} · {p.type.toLowerCase().replaceAll('_',' ')}{p.hidden?' · hidden':''}</span><div className="row"><button disabled={database.archived} onClick={()=>choose(p)}>Edit {p.name}</button><button disabled={database.archived||command.busy||i===0} onClick={async()=>{const ids=properties.map(p=>p.id);[ids[i-1],ids[i]]=[ids[i]!,ids[i-1]!];if(await command.send(`/knowledge/databases/${database.id}/reorder`,{version:database.version,ids}))onSaved();}}>Move {p.name} up</button><button disabled={database.archived||command.busy||p.type==='TITLE'} onClick={async()=>{if(await command.send(`/knowledge/databases/${database.id}/properties/${p.id}`,{version:database.version},'DELETE'))onSaved();}}>Remove {p.name}</button></div></li>)}</ol>
    <form className="knowledge-form" aria-label={edit?'Edit property':'Add property'} onSubmit={async e=>{e.preventDefault();if(await command.send(`/knowledge/databases/${database.id}/properties${edit?'/'+edit.id:''}`,{version:database.version,property:{name,type,hidden,config:{options:['SELECT','MULTI_SELECT'].includes(type)?options.split('\n').map(s=>s.trim()).filter(Boolean):[],relationKind:kind,relationDatabaseId:type==='RELATION'&&kind==='record'&&related?related:null}}},edit?'PATCH':'POST'))onSaved();}}><fieldset disabled={database.archived||command.busy}><legend>{edit?'Edit property':'Add property'}</legend><label>Property name<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label>Property type<select disabled={!!edit} value={type} onChange={e=>setType(e.target.value as typeof type)}>{KNOWLEDGE_TYPES.filter(t=>t!=='TITLE'||edit?.type==='TITLE').map(t=><option key={t} value={t}>{t.toLowerCase().replaceAll('_',' ')}</option>)}</select></label>{['SELECT','MULTI_SELECT'].includes(type)&&<label>Choices, one per line<textarea required value={options} onChange={e=>setOptions(e.target.value)}/></label>}{type==='RELATION'&&<><label>Link to<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}>{knowledgeTargetKind.options.map(k=><option key={k}>{k}</option>)}</select></label>{kind==='record'&&<label>Related database<select value={related} onChange={e=>setRelated(e.target.value)}><option value="">Any database</option>{databases.data?.data.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>}</>}<label className="row"><input type="checkbox" disabled={type==='TITLE'} checked={hidden} onChange={e=>setHidden(e.target.checked)}/>Hide in views</label><button>{edit?'Save property':'Add property'}</button>{edit&&<button type="button" onClick={()=>{setEdit(null);setName('');setType('TEXT');setOptions('');setHidden(false);}}>Cancel edit</button>}</fieldset></form>
  </section>;
}
export function RecordForm({properties,path,initial,onSaved,disabled=false}:{properties:Property[];path:string;initial?:KnowledgeItemDraft;onSaved:()=>void;disabled?:boolean}) {
  const [title,setTitle]=useState(initial?.title??''),[content,setContent]=useState(initial?.content??''),[values,setValues]=useState<Record<string,KnowledgeValue>>(initial?.values??{});const command=useKnowledgeCommand();
  return <form className="card knowledge-form" aria-label={initial?'Edit record':'New record'} onSubmit={async e=>{e.preventDefault();if(await command.send(path,{title,content,values,...(initial?{version:initial.version}:{})},initial?'PATCH':'POST'))onSaved();}}><fieldset disabled={disabled||command.busy}><legend>{initial?'Edit record':'New record'}</legend><label>{properties.find(p=>p.type==='TITLE')?.name??'Title'}<input required maxLength={500} value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="knowledge-grid">{properties.filter(p=>!['TITLE','FILE','RELATION'].includes(p.type)).map(p=><ValueInput key={p.id} property={p} value={values[p.id]} onChange={v=>setValues(old=>({...old,[p.id]:v}))}/>)}</div><label>Record content (Markdown)<textarea rows={8} maxLength={20000} value={content} onChange={e=>setContent(e.target.value)}/></label><button>{initial?'Save record':'Add record'}</button></fieldset><KnowledgeStatus error={command.error}/></form>;
}
interface KnowledgeItemDraft{title:string;content:string;version:number;values:Record<string,KnowledgeValue>;}
