'use client';
import Link from 'next/link';
import { useCallback,useEffect,useRef,useState } from 'react';
import type { CalendarSource,CenterEvent } from '@nextdoo/contracts';
import { localParts,localDateKey,zonedTimeToUtc } from '@nextdoo/core/calendar';
import { api } from '@/lib/api';
import { CalendarSettings } from './CalendarSettings';
import { errorMessage,KnowledgeStatus,useKnowledgeCommand } from './knowledge/shared';

export function useCalendarCenter(start:string,end:string,workspaceTimeZone:string){
  const [sources,setSources]=useState<CalendarSource[]>([]),[events,setEvents]=useState<CenterEvent[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
  const command=useKnowledgeCommand();const refresh=useCallback(()=>setRevision(v=>v+1),[]);
  useEffect(()=>{const c=new AbortController();setLoading(true);setError('');setEvents([]);
    void(async()=>{try{const result=await api<{data:CalendarSource[]}>('/calendar/center/sources',{signal:c.signal});if(c.signal.aborted)return;setSources(result.data);
      let offset:number|null=0;const rows=new Map<string,CenterEvent>();while(offset!==null){const page:{data:CenterEvent[];nextOffset:number|null}=await api<{data:CenterEvent[];nextOffset:number|null}>(`/calendar/center/events?${new URLSearchParams({start,end,offset:String(offset),limit:'200'})}`,{signal:c.signal});if(c.signal.aborted)return;for(const event of page.data)rows.set(event.id,event);setEvents([...rows.values()]);offset=page.nextOffset;}
    }catch(e){if(!c.signal.aborted)setError(errorMessage(e));}finally{if(!c.signal.aborted)setLoading(false);}})();return()=>c.abort();},[start,end,revision]);
  useEffect(()=>{window.addEventListener('nextdoo-synced',refresh);return()=>window.removeEventListener('nextdoo-synced',refresh);},[refresh]);
  async function update(source:CalendarSource,changes:Partial<Pick<CalendarSource,'name'|'color'|'visible'|'archived'>>){
    if(changes.visible!==undefined)setSources(old=>old.map(s=>s.id===source.id?{...s,visible:changes.visible!}:s));
    const result=await command.send<CalendarSource>(`/calendar/center/sources/${encodeURIComponent(source.id)}`,{version:source.version,...changes},'PATCH');
    if(result)setSources(old=>old.map(s=>s.id===source.id?result:s));
    else if(changes.visible!==undefined)setSources(old=>old.map(s=>s.id===source.id&&s.version===source.version?{...s,visible:source.visible}:s));
    return !!result;
  }
  const visible=(id:string)=>{const source=sources.find(s=>s.id===id);return source?source.visible&&!source.archived:true;};
  const color=(id:string)=>sources.find(s=>s.id===id)?.color??'#315ca8';
  async function move(id:string,day:Date,resize=false){
    const event=events.find(e=>e.id===id);if(!event||event.kind!=='NATIVE')return;
    const moveZone=event.isAllDay?event.timeZone:workspaceTimeZone;
    const p=localParts(day,workspaceTimeZone),original=localParts(new Date(resize?event.endsAt:event.startsAt),moveZone);
    const target=zonedTimeToUtc(p.year,p.month,p.day,original.hour,original.minute,moveZone);
    let startsAt=resize?event.startsAt:target.toISOString(),endsAt=resize?target.toISOString():new Date(target.getTime()+new Date(event.endsAt).getTime()-new Date(event.startsAt).getTime()).toISOString();
    if(event.isAllDay&&!resize){const span=(Date.parse(event.endDay!)-Date.parse(event.startDay!))/86400000,d=new Date(Date.UTC(p.year,p.month-1,p.day+span));endsAt=zonedTimeToUtc(d.getUTCFullYear(),d.getUTCMonth()+1,d.getUTCDate(),0,0,event.timeZone).toISOString();startsAt=zonedTimeToUtc(p.year,p.month,p.day,0,0,event.timeZone).toISOString();}
    if(await command.send(`/calendar/center/events/${id}`,{version:event.version,event:{sourceId:event.sourceId,title:event.title,description:event.description,location:event.location,startsAt,endsAt,timeZone:event.timeZone,isAllDay:event.isAllDay}},'PATCH'))refresh();
  }
  return {sources,events:events.filter(e=>visible(e.sourceId)),error:error||command.error,loading,busy:command.busy,refresh,update,visible,color,move};
}
type Center=ReturnType<typeof useCalendarCenter>;
export function CalendarSourcePanel({center,timeZone,onAddEvent}:{center:Center;timeZone:string;onAddEvent:()=>void}){
  const [adding,setAdding]=useState(false),[importing,setImporting]=useState(false),[google,setGoogle]=useState(false),[expanded,setExpanded]=useState(true);
  useEffect(()=>{setExpanded(!window.matchMedia('(max-width:800px)').matches);},[]);
  return <aside className="calendar-sources" aria-label="Calendars"><h2>Calendars</h2><div className="row calendar-actions"><button disabled={center.loading} onClick={onAddEvent}>Add event</button><button onClick={()=>setAdding(v=>!v)}>Add Calendar</button><button onClick={()=>setImporting(v=>!v)}>Import Calendar</button></div>
    {adding&&<div className="card"><NewCalendar timeZone={timeZone} onSaved={()=>{setAdding(false);center.refresh();}}/><button onClick={()=>setGoogle(v=>!v)}>Connect Google Calendar</button><p className="muted">Google primary-calendar sync. Outlook and Apple connections are not available yet.</p></div>}
    {importing&&<ImportCalendar sources={center.sources} timeZone={timeZone} onSaved={()=>{setImporting(false);center.refresh();}}/>}
    <KnowledgeStatus loading={center.loading} error={center.error}/>
    <button aria-expanded={expanded} onClick={()=>setExpanded(v=>!v)}>{expanded?'Hide calendar sources':'Show calendar sources'}</button><div hidden={!expanded}>
    {(['INTERNAL','NATIVE','GOOGLE','ICS'] as const).map(kind=><section key={kind} aria-label={kind==='INTERNAL'?'Connected calendar layers':kind==='GOOGLE'?'Connected Google calendars':kind==='ICS'?'Imported calendars':'My calendars'}><h3>{kind==='INTERNAL'?'NextDoo sources':kind==='GOOGLE'?'Connected':kind==='ICS'?'Imported':'My calendars'}</h3>{center.sources.filter(s=>s.kind===kind).map(source=><div key={source.id} className="calendar-source"><label><input type="checkbox" checked={source.visible&&!source.archived} disabled={source.archived||center.busy} onChange={e=>void center.update(source,{visible:e.target.checked})}/><span className="source-dot" style={{background:source.color}}/>{source.name}</label><small>{source.status.toLowerCase()} · {source.writable?'editable':'read-only'}</small><details><summary>Settings for {source.name}</summary><SourceSettings key={source.id+source.version} source={source} center={center}/></details></div>)}{!center.sources.some(s=>s.kind===kind)&&<p className="muted">No calendars yet.</p>}</section>)}
    <button onClick={()=>setGoogle(v=>!v)}>Manage Google connection</button>{google&&<CalendarSettings/>}<p className="muted">Hiding a source keeps its data. Source visibility does not change workload or capacity.</p><button onClick={center.refresh}>Refresh calendars</button></div>
  </aside>;
}
function SourceSettings({source,center}:{source:CalendarSource;center:Center}){
  const [name,setName]=useState(source.name),[color,setColor]=useState(source.color),[error,setError]=useState('');
  async function download(){try{const result=await api<{content:string}>(`/calendar/center/sources/${source.id}/export`),url=URL.createObjectURL(new Blob([result.content],{type:'text/calendar;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='nextdoo-calendar.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(errorMessage(e));}}
  return <div><p className="muted">{source.detail}</p><form onSubmit={async e=>{e.preventDefault();await center.update(source,{name,color});}}><label>Calendar name<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Calendar color<input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><button disabled={center.busy}>Save calendar settings</button></form>{['NATIVE','ICS'].includes(source.kind)&&<><button disabled={center.busy} onClick={()=>void center.update(source,{archived:!source.archived})}>{source.archived?'Restore calendar':'Archive calendar'}</button><button onClick={()=>void download()}>Download ICS</button><small>Private download, not a live subscription.</small></>}<KnowledgeStatus error={error}/></div>;
}
function NewCalendar({timeZone,onSaved}:{timeZone:string;onSaved:()=>void}){
  const [name,setName]=useState('Personal'),[zone,setZone]=useState(timeZone),command=useKnowledgeCommand();
  return <form aria-label="New calendar" onSubmit={async e=>{e.preventDefault();if(await command.send('/calendar/center/sources',{name,timeZone:zone}))onSaved();}}><h3>New NextDoo calendar</h3><label>New calendar name<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Calendar time zone<input required value={zone} onChange={e=>setZone(e.target.value)}/></label><KnowledgeStatus error={command.error}/><button disabled={command.busy}>Create calendar</button></form>;
}
function ImportCalendar({sources,timeZone,onSaved}:{sources:CalendarSource[];timeZone:string;onSaved:()=>void}){
  const [name,setName]=useState('Imported calendar'),[content,setContent]=useState(''),[sourceId,setSource]=useState(''),[error,setError]=useState('');
  const year=new Date().getFullYear(),[from,setFrom]=useState(`${year}-01-01`),[through,setThrough]=useState(`${year+1}-01-01`),command=useKnowledgeCommand();
  return <form className="card" aria-label="Import ICS" onSubmit={async e=>{e.preventDefault();const source=sources.find(s=>s.id===sourceId);if(await command.send('/calendar/center/import',{name,content,timeZone,from,through,...(source?{sourceId:source.id,version:source.version,color:source.color}:{})}))onSaved();}}><h3>Import ICS snapshot</h3><p>Upload a calendar file (up to 1 MB, 2000 occurrences). Recurring events are expanded only in your chosen window. Re-import replaces the selected snapshot. No tasks are created.</p><label>Import name<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Destination<select value={sourceId} onChange={e=>{setSource(e.target.value);const selected=sources.find(s=>s.id===e.target.value);if(selected)setName(selected.name);}}><option value="">New imported calendar</option>{sources.filter(s=>s.kind==='ICS'&&!s.archived).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>ICS file<input type="file" accept=".ics,text/calendar" required onChange={async e=>{setError('');setContent('');const file=e.target.files?.[0];if(!file)return;if(file.size>1000000){setError('Choose a file of 1 MB or less.');return;}setContent(await file.text());}}/></label><label>Import from<input type="date" required value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Import until (exclusive)<input type="date" required value={through} onChange={e=>setThrough(e.target.value)}/></label><p className="muted">Floating times use {timeZone}. For an ICS URL, download the file first. URL subscriptions are not supported.</p><KnowledgeStatus error={error||command.error}/><button disabled={command.busy||!content}>Import snapshot</button></form>;
}
const wall=(iso:string,zone:string)=>{const p=localParts(new Date(iso),zone);return `${p.year}-${String(p.month).padStart(2,'0')}-${String(p.day).padStart(2,'0')}T${String(p.hour).padStart(2,'0')}:${String(p.minute).padStart(2,'0')}`;};
function utc(value:string,zone:string){const [date,time='00:00']=value.split('T'),[y,m,d]=date!.split('-').map(Number),[h,min]=time.split(':').map(Number);return zonedTimeToUtc(y!,m!,d!,h!,min!,zone).toISOString();}
export function CalendarEventDialog({event,sources,timeZone,onClose,onSaved}:{event:CenterEvent|null;sources:CalendarSource[];timeZone:string;onClose:()=>void;onSaved:()=>void}){
  const ref=useRef<HTMLDialogElement>(null),command=useKnowledgeCommand();const native=sources.filter(s=>s.kind==='NATIVE'&&!s.archived);
  const [current,setCurrent]=useState(event),[title,setTitle]=useState(event?.title??''),[description,setDescription]=useState(event?.description??''),[location,setLocation]=useState(event?.location??''),[sourceId,setSource]=useState(event?.sourceId??native[0]?.id??''),[zone,setZone]=useState(event?.timeZone??timeZone),[allDay,setAllDay]=useState(event?.isAllDay??false),[error,setError]=useState('');
  const [start,setStart]=useState(event?event.isAllDay?event.startDay!:wall(event.startsAt,zone):wall(new Date().toISOString(),zone)),[end,setEnd]=useState(event?event.isAllDay?event.endDay!:wall(event.endsAt,zone):wall(new Date(Date.now()+3600000).toISOString(),zone));
  useEffect(()=>{const dialog=ref.current;dialog?.showModal();return()=>dialog?.close();},[]);
  const readOnly=!!current&&(current.kind!=='NATIVE'||!native.some(s=>s.id===current.sourceId));
  async function reload(){if(!current)return;try{const row=await api<CenterEvent>(`/calendar/center/events/${current.id}`);setCurrent({...current,...row});setTitle(row.title);setDescription(row.description);setLocation(row.location);setSource(row.sourceId);setZone(row.timeZone);setAllDay(row.isAllDay);setStart(row.isAllDay?row.startDay!:wall(row.startsAt,row.timeZone));setEnd(row.isAllDay?row.endDay!:wall(row.endsAt,row.timeZone));}catch(e){setError(errorMessage(e));}}
  return <dialog ref={ref} className="calendar-event-dialog" aria-label={current?'Calendar event':'New calendar event'} onCancel={e=>{e.preventDefault();if(!command.busy)onClose();}}><button type="button" disabled={command.busy} onClick={onClose}>Close event</button><h2>{current?current.title:'New event'}</h2>{readOnly?<><p>Read-only {current!.kind.toLowerCase()} event.</p><p>{current!.isAllDay?`${current!.startDay} – ${current!.endDay} (end exclusive)`:`${new Date(current!.startsAt).toLocaleString(undefined,{timeZone:current!.timeZone})} – ${new Date(current!.endsAt).toLocaleString(undefined,{timeZone:current!.timeZone})}`}</p><p>{current!.description}</p><p>{current!.location}</p><p>Event time zone: {current!.timeZone}</p>{current!.taskId&&<Link href={`/tasks/${current!.taskId}`}>Open linked Task to edit through existing sync</Link>}</>:<form aria-label="Calendar event editor" onSubmit={async e=>{e.preventDefault();setError('');try{const input={sourceId,title,description,location,timeZone:zone,isAllDay:allDay,startsAt:utc(start,zone),endsAt:utc(end,zone)};if(await command.send(current?`/calendar/center/events/${current.id}`:'/calendar/center/events',current?{version:current.version,event:input}:input,current?'PATCH':'POST')){onSaved();onClose();}}catch{setError('Choose valid dates and a supported IANA time zone.');}}}>
    {!native.length&&<p>Create a NextDoo calendar using Add Calendar first.</p>}<label>Event title<input required maxLength={500} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Event calendar<select required value={sourceId} onChange={e=>setSource(e.target.value)}><option value="">Choose calendar</option>{native.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Event time zone<input required value={zone} onChange={e=>setZone(e.target.value)}/></label><label className="row"><input type="checkbox" checked={allDay} onChange={e=>{const checked=e.target.checked;setAllDay(checked);if(checked){setStart(start.slice(0,10));const d=new Date(start.slice(0,10)+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+1);setEnd(d.toISOString().slice(0,10));}else{setStart(start.slice(0,10)+'T09:00');setEnd(end.slice(0,10)+'T09:00');}}}/>All-day</label><label>Event start<input required type={allDay?'date':'datetime-local'} value={start} onChange={e=>setStart(e.target.value)}/></label><label>{allDay?'Event end (exclusive date)':'Event end'}<input required type={allDay?'date':'datetime-local'} value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Event location<input maxLength={1000} value={location} onChange={e=>setLocation(e.target.value)}/></label><label>Event description<textarea maxLength={20000} value={description} onChange={e=>setDescription(e.target.value)}/></label><p className="muted">One-off event. Recurrence and reminders remain available on Tasks.</p><KnowledgeStatus error={error||command.error}/><button disabled={command.busy||!native.length}>Save event</button>{current&&<><button type="button" disabled={command.busy} onClick={()=>void reload()}>Reload saved event</button><button type="button" disabled={command.busy} onClick={async()=>{if(await command.send(`/calendar/center/events/${current.id}`,{version:current.version},'DELETE')){onSaved();onClose();}}}>Delete event</button></>}</form>}</dialog>;
}
export function eventOnDay(event:CenterEvent,day:string,zone:string){if(event.isAllDay)return day>=event.startDay!&&day<event.endDay!;return day>=localDateKey(new Date(event.startsAt),zone)&&day<=localDateKey(new Date(new Date(event.endsAt).getTime()-1),zone);}
export function CalendarEventChip({event,color,onOpen,timeZone}:{event:CenterEvent;color:string;onOpen:()=>void;timeZone:string}){return <div className={`cal-chip ${event.kind==='GOOGLE'?'cal-external':'cal-native'}`} style={{borderLeft:`4px solid ${color}`}} onClick={e=>e.stopPropagation()} draggable={event.kind==='NATIVE'} onDragStart={e=>{e.stopPropagation();e.dataTransfer.setData('application/x-nextdoo-event',event.id);}}>{event.kind==='GOOGLE'&&<span className="cal-ext-tag">cal</span>}<button className="cal-title btn-sm" onClick={onOpen}>{event.title}</button><small>{event.isAllDay?'All day':new Date(event.startsAt).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit',timeZone})} · {event.kind==='ICS'?'import':event.kind.toLowerCase()}</small>{event.kind==='NATIVE'&&<span className="event-resize" draggable title="Drag to another day to change the end; or edit Event end" onDragStart={e=>{e.stopPropagation();e.dataTransfer.setData('application/x-nextdoo-resize',event.id);}}>↔</span>}</div>;}
