'use client';
import Link from 'next/link';
import { useEffect,useRef,useState } from 'react';
import type { ConnectedItem,ConnectedPage } from '@nextdoo/contracts';
import { api } from '@/lib/api';
import { errorMessage } from './knowledge/shared';

const destinations=[['Home','/home'],['Inbox','/inbox'],['Today','/today'],['Tomorrow','/tomorrow'],['Upcoming','/upcoming'],['Focus','/focus'],['Completed','/completed'],['Goals','/goals'],['Trackers','/trackers'],['Knowledge','/knowledge'],['Calendar','/calendar'],['Insights','/insights'],['Projects','/projects'],['Search','/search'],['Notifications','/notifications']] as const;
export function CommandPalette(){
  const [open,setOpen]=useState(false);
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{const target=e.target as HTMLElement|null;if(e.key==='?'&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!e.repeat&&!target?.closest('input,textarea,select,[contenteditable],dialog')){e.preventDefault();setOpen(true);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
  return <><button className="command-launcher" aria-haspopup="dialog" aria-keyshortcuts="?" onClick={()=>setOpen(true)}>Commands <span aria-hidden="true">?</span></button>{open&&<Palette onClose={()=>setOpen(false)}/>}</>;
}
function Palette({onClose}:{onClose:()=>void}){
  const ref=useRef<HTMLDialogElement>(null),input=useRef<HTMLInputElement>(null),[query,setQuery]=useState(''),[items,setItems]=useState<ConnectedItem[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  useEffect(()=>{const prior=document.activeElement as HTMLElement|null,dialog=ref.current;dialog?.showModal();input.current?.focus();return()=>{dialog?.close();if(prior?.isConnected)prior.focus();};},[]);
  useEffect(()=>{const controller=new AbortController();setItems([]);setError('');setLoading(!!query.trim());const timer=setTimeout(()=>{if(!query.trim())return;void api<ConnectedPage<ConnectedItem>>('/connected/search?limit=8&q='+encodeURIComponent(query),{signal:controller.signal}).then(result=>{if(!controller.signal.aborted)setItems(result.data);}).catch(e=>{if(!controller.signal.aborted)setError(errorMessage(e));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},200);return()=>{clearTimeout(timer);controller.abort();};},[query]);
  const actions=[['Create a task','/inbox#capture'],['Start Focus','/focus'],...destinations.map(([name,href])=>['Open '+name,href])].filter(([name])=>name!.toLowerCase().includes(query.toLowerCase()));
  return <dialog ref={ref} className="command-palette" aria-labelledby="command-title" onCancel={e=>{e.preventDefault();onClose();}} onKeyDown={e=>{if(e.key==='Tab'){const controls=Array.from(ref.current!.querySelectorAll<HTMLElement>('button,input,a[href]')).filter(node=>!node.hasAttribute('disabled'));const first=controls[0],last=controls[controls.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}return;}if(e.key!=='ArrowDown'&&e.key!=='ArrowUp')return;const links=Array.from(ref.current!.querySelectorAll<HTMLAnchorElement>('a'));if(!links.length)return;e.preventDefault();const index=links.indexOf(document.activeElement as HTMLAnchorElement);links[index<0?(e.key==='ArrowDown'?0:links.length-1):(index+(e.key==='ArrowDown'?1:-1)+links.length)%links.length]?.focus();}}><div className="row"><h2 id="command-title">Commands</h2><button onClick={onClose}>Close commands</button></div><label>Find a command or item<input ref={input} maxLength={200} value={query} onChange={e=>setQuery(e.target.value)}/></label><p className="muted">Tab or arrow keys to browse, Enter to open, Escape to close. Search requires a connection.</p><ul>{actions.map(([name,href])=><li key={name}><Link href={href!} onClick={()=>{onClose();if(href==='/inbox#capture')setTimeout(()=>document.getElementById('capture')?.focus(),0);}}>{name}</Link></li>)}</ul>{query.trim()&&<><h3>Matching items</h3><p role="status">{loading?'Searching…':error||`${items.length} matching items shown`}</p><ul>{items.map(item=><li key={item.type+item.id}><Link href={item.href!} onClick={onClose}>{item.title}</Link><small> · {item.detail}</small></li>)}</ul><Link href={'/search?q='+encodeURIComponent(query)} onClick={onClose}>See all search results</Link></>}</dialog>;
}
