'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import type { Personalization } from '@nextdoo/contracts';
import { usePersonalization } from './PersonalizationContext';
import { api } from '@/lib/api';
export function PersonalizationSettings({section}:{section:'appearance'|'productivity'|'notifications'}){
  const {preferences,save,busy}=usePersonalization();const [error,setError]=useState(''),[notice,setNotice]=useState(''),[projects,setProjects]=useState<{id:string;name:string;status:string}[]>([]);
  useEffect(()=>{if(section==='productivity')void api<{data:{id:string;name:string;status:string}[]}|{id:string;name:string;status:string}[]>('/projects').then(r=>setProjects(Array.isArray(r)?r:r.data)).catch(()=>setError('Could not load task lists. Reload Settings to try again.'));},[section]);
  async function change(patch:Partial<Personalization>){setError('');setNotice('');try{await save(patch);setNotice('Preferences saved.');}catch(e){setError(e instanceof Error?e.message:'Could not save. Your saved preference remains unchanged.');}}
  const select=(key:keyof Personalization,label:string,options:[string,string][])=> <div className="field" key={key}><label htmlFor={'pref-'+key}>{label}</label><select id={'pref-'+key} disabled={busy} value={String(preferences[key]??'')} onChange={e=>void change({[key]:key==='defaultTaskList'?(e.target.value||null):e.target.value})}>{options.map(([value,title])=><option key={value} value={value}>{title}</option>)}</select></div>;
  return <section className="card" aria-label={section==='appearance'?'Appearance preferences':section==='productivity'?'Productivity preferences':'Notification defaults'}>
    <h2>{section==='appearance'?'Appearance':section==='productivity'?'Productivity defaults':'Notification defaults'}</h2>
    {section==='appearance'&&<>{select('theme','Theme',[['system','System'],['light','Light'],['dark','Dark']])}{select('accent','Accent color',[['blue','Blue'],['purple','Purple'],['green','Green']])}{select('density','Density',[['comfortable','Comfortable'],['compact','Compact']])}{select('uiSize','Text size',[['standard','Standard'],['large','Large']])}{select('sidebar','Desktop sidebar',[['expanded','Expanded'],['compact','Compact icons']])}<p>Saved to your account and applied across the app. System appearance follows your device.</p></>}
    {section==='productivity'&&<>{select('startPage','Start page',[['/today','Today'],['/inbox','Inbox'],['/tasks','Browse tasks'],['/goals','Goals'],['/trackers','Tracker'],['/knowledge','Knowledge & Data'],['/projects','Projects'],['/calendar','Calendar'],['/insights','Insights']])}{select('defaultTaskView','Default project task view',[['list','List'],['board','Board']])}{select('defaultTaskList','Default task list',[['','Inbox / unfiled'],...projects.filter(p=>p.status==='ACTIVE').map(p=>[p.id,p.name] as [string,string])])}<p>Quick capture uses this list unless you name a project explicitly. Existing tasks and Inbox filters stay unchanged. Archived or deleted defaults fall back to Inbox on reload.</p>{select('calendarView','Default Calendar view',[['day','Day'],['week','Week'],['month','Month'],['year','Year'],['agenda','Agenda']])}{select('insightsPeriod','Default Insights period',[['day','Daily'],['week','Weekly'],['month','Monthly'],['quarter','Quarterly'],['year','Yearly']])}<p>Defaults apply when opening a module; explicit report links retain their selected dates.</p><p><Link href="/trackers">Tracker definitions and report delivery</Link> remain in each tracker's Settings panel.</p></>}
    {section==='notifications'&&<>{select('reminderChannel','Default reminder delivery',[['WEB','In-app'],['PUSH','Browser push (enable below)']])}<form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);void change({reminderMinutes:Number(data.get('minutes'))});}}><label htmlFor="pref-reminder-minutes">Default minutes before due</label><input key={preferences.reminderMinutes} id="pref-reminder-minutes" name="minutes" type="number" min={0} max={43200} required defaultValue={preferences.reminderMinutes} disabled={busy} /><button disabled={busy}>Save reminder default</button></form><p>Prefills new reminder forms; it does not create reminders or change existing deliveries. Push requires permission and a device subscription. Email is currently used for account messages and configured Tracker reports, not general task-reminder delivery.</p><Link href="/notifications">Manage reminders and delivery history</Link></>}
    {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
  </section>;
}
