'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { api } from '@/lib/api';
import { pendingSummary } from '@/lib/offline-queue';
import { useWorkspace } from './WorkspaceContext';
import type { SettingsCenterStatus } from '@/server/services/settings-center';
export function useSettingsStatus(){const [status,setStatus]=useState<SettingsCenterStatus|null>(null),[error,setError]=useState('');useEffect(()=>{const c=new AbortController();void api<SettingsCenterStatus>('/settings/status',{signal:c.signal}).then(setStatus).catch(()=>{if(!c.signal.aborted)setError('Could not load plan and storage details. Reload Settings to retry.');});return ()=>c.abort();},[]);return {status,error};}
const bytes=(n:number)=>`${(n/1024/1024).toLocaleString(undefined,{maximumFractionDigits:2})} MB`;
export function SyncDataSettings({status}:{status:SettingsCenterStatus|null}){
  const {id}=useWorkspace();const [online,setOnline]=useState(true),[queue,setQueue]=useState<{queued:number;attention:number}|null>(null);
  useEffect(()=>{let live=true;const update=()=>{setOnline(navigator.onLine);void pendingSummary(id).then(r=>{if(live)setQueue(r);});};update();for(const e of ['online','offline','nextdoo-queue-changed','nextdoo-synced'])window.addEventListener(e,update);const interval=setInterval(update,5000);return ()=>{live=false;clearInterval(interval);for(const e of ['online','offline','nextdoo-queue-changed','nextdoo-synced'])window.removeEventListener(e,update);};},[id]);
  return <section className="card" aria-label="Sync and storage"><h2>Sync & storage</h2><p role="status">{online?'Online':'Offline'} · {queue?`${queue.queued} queued changes · ${queue.attention} need attention`:'Checking this device’s queue…'}</p><Link href="/conflicts">Review sync conflicts</Link><p>This device's existing sync queue reconnects automatically. Offline capture and supported task edits retain their existing behavior. Goals, Tracker, Knowledge, Calendar editing, reports and Settings require a connection.</p><p>{status?`Attachment storage: ${bytes(status.storageBytes)} of ${bytes(status.entitlements.limits.attachmentStorageBytes)}. Maximum file: ${bytes(status.entitlements.limits.maxFileBytes)}.`:'Loading storage usage…'}</p><p>Usage includes reserved uploads and quarantined files until deleted. Remove files from their original task, goal, record or note to release space.</p><p><Link href="/calendar">Import an ICS calendar snapshot</Link> · <Link href="/trackers">Tracker template import/export</Link></p><p>Account exports contain data and attachment metadata, not attachment file bytes. Automated database backup/restore is operated by the deployment administrator; there is no self-service restore button.</p></section>;
}
export function PlanSettings({status}:{status:SettingsCenterStatus|null}){
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  async function upgrade(){setBusy(true);setError('');try{const result=await api<{method:string;redirectUrl?:string}>('/billing/checkout',{method:'POST',body:JSON.stringify({plan:'PRO',provider:'STRIPE'})});if(result.method!=='REDIRECT'||!result.redirectUrl)throw new Error('This checkout handoff cannot be opened here.');const url=new URL(result.redirectUrl);if(url.protocol!=='https:')throw new Error('The checkout URL is unavailable.');window.location.assign(url.href);}catch(e){setError(e instanceof Error?e.message:'Checkout unavailable.');setBusy(false);}}
  return <section className="card" aria-label="Plan and billing"><h2>Plan & billing</h2>{status?<><p>Current access: <strong>{status.subscription.effectivePlan}</strong> · Subscription: {status.subscription.status}</p><p>Recorded plan: {status.subscription.plan}. {status.subscription.currentPeriodEnd&&`Current period ends ${new Date(status.subscription.currentPeriodEnd).toLocaleDateString()}.`} {status.subscription.cancelAtPeriodEnd&&'Cancellation is scheduled at period end.'} {status.subscription.pendingPlan&&`Next plan: ${status.subscription.pendingPlan}.`} {status.subscription.graceEndsAt&&`Payment grace ends ${new Date(status.subscription.graceEndsAt).toLocaleDateString()}.`}</p><p>Tracking history: {status.entitlements.limits.trackingHistoryDays??'Unlimited'} days · Exports per day: {status.entitlements.limits.exportsPerDay??'Unlimited'} · Audit retention: {status.entitlements.limits.auditLogRetentionDays} days.</p>{status.checkout.stripe&&status.subscription.effectivePlan==='FREE'?<button disabled={busy} onClick={()=>void upgrade()}>Upgrade to Pro with Stripe</button>:<p>{status.checkout.stripe?'Your current plan is shown above.':'Online Stripe checkout is not configured on this deployment.'}</p>}{status.checkout.razorpay&&<p>Razorpay's backend is configured; embedded checkout is not available in this interface.</p>}<p>Payments update access only after provider confirmation. Subscription management and cancellation use your billing provider's existing support channel; no in-app portal is implemented.</p></>:<p role="status">Loading billing state…</p>}{error&&<p role="alert">{error}</p>}</section>;
}
export function SettingsHelp(){return <section className="card" aria-label="Help and guidance"><h2>Help</h2><h3>Get started</h3><ol><li>Create a goal and milestones, then link your existing tasks.</li><li>Capture tasks in Inbox or Today; use +project names to choose a list.</li><li>Record observations in Tracker and keep notes or records in Knowledge & Data.</li><li>Review dates in Calendar and summarize your work in Insights.</li></ol><h3>Useful guides</h3><p><Link href="/notifications">Scheduling reminders</Link> · <Link href="/conflicts">Resolving sync conflicts</Link> · <Link href="/insights/reports">Creating a report</Link></p><p><a href="https://github.com/Sudhanshu-git-hub/Nextdoo/blob/main/docs/PRD.md" target="_blank" rel="noreferrer">Product documentation</a> · <a href="https://github.com/Sudhanshu-git-hub/Nextdoo/commits/main/" target="_blank" rel="noreferrer">Changelog</a> · <a href="https://github.com/Sudhanshu-git-hub/Nextdoo/issues" target="_blank" rel="noreferrer">Feedback and support issues</a></p><p>Repository access may be required. Share reproducible steps and request IDs, not passwords, tokens or private report data. The current interface is English; dates and numbers use supported browser locale formatting.</p><h3>Privacy</h3><p>Settings are scoped to your account. Provider secrets and session tokens are never shown here. Export and deletion controls are in Sync & Data; MFA and device sessions are in Security & Privacy.</p></section>;}
