'use client';
import Link from 'next/link';
import { useState } from 'react';
import type { ConnectedItem,ConnectedPage } from '@nextdoo/contracts';
import { api } from '@/lib/api';
import { useKnowledgeRead,useKnowledgeCommand,KnowledgeStatus,KnowledgePager,errorMessage } from './knowledge/shared';
export function TaskWorkspaceLinks({id,disabled=false}:{id:string;disabled?:boolean}){
  const [offset,setOffset]=useState(0),[picking,setPicking]=useState(false),[type,setType]=useState('goal'),[q,setQ]=useState(''),[draft,setDraft]=useState(''),[page,setPage]=useState(0),[selected,setSelected]=useState<ConnectedItem|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  const read=useKnowledgeRead<ConnectedPage<ConnectedItem>>(`/connected/tasks/${id}?offset=${offset}`),search=useKnowledgeRead<ConnectedPage<ConnectedItem>>(`/connected/search?type=${type}&q=${encodeURIComponent(q)}&offset=${page}`),command=useKnowledgeCommand();
  const locked=disabled||loading||command.busy;
  async function choose(item:ConnectedItem){setLoading(true);setError('');setSelected(null);try{const detail=await api<{version?:number;goal?:{version:number};tracker?:{version:number}}>(`/${item.type==='milestone'?'milestones':item.type==='tracker'?'trackers':'goals'}/${item.id}`);setSelected({...item,version:detail.version??detail.goal?.version??detail.tracker?.version});}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
  async function mutate(item:ConnectedItem,linked:boolean){if(await command.send(`/${item.type==='milestone'?'milestones':item.type==='tracker'?'trackers':'goals'}/${item.id}/tasks`,{version:item.version,taskId:id,linked})){setSelected(null);setPicking(false);read.refresh();}}
  return <section className="card" aria-label="Connected work"><h3>Goals, milestones &amp; trackers</h3><p className="muted">Links use the original module. Linking needs a connection.</p><KnowledgeStatus error={read.error||error||command.error} loading={read.loading||loading}/>{read.data&&!read.error&&<><ul className="connected-links">{read.data.data.map(item=><li key={item.type+item.id}><Link href={item.href!}>{item.title}</Link><span> · {item.detail} · {item.state?.toLowerCase()}</span>{item.direct?<button type="button" disabled={locked||read.loading} onClick={()=>void mutate(item,false)}>Unlink {item.title}</button>:<small> · Via a milestone; remove the milestone link to disconnect this path.</small>}</li>)}</ul>{!read.data.data.length&&<p>No linked goals or trackers.</p>}<KnowledgePager offset={offset} nextOffset={read.data.nextOffset} setOffset={setOffset} label="Connected work pages"/></>}
  <button type="button" disabled={locked} onClick={()=>{setPicking(v=>!v);setSelected(null);}}>Link existing work</button><button type="button" disabled={locked} onClick={()=>{read.refresh();if(selected)void choose(selected);}}>Reload saved version</button><p><Link href={`/notifications?taskId=${id}`}>Task reminders</Link></p>
  {picking&&<div><form className="row" onSubmit={e=>{e.preventDefault();setQ(draft);setPage(0);setSelected(null);}}><label>Link type<select disabled={locked} value={type} onChange={e=>{setType(e.target.value);setPage(0);setSelected(null);}}><option value="goal">Goal</option><option value="milestone">Milestone</option><option value="tracker">Tracker</option></select></label><label>Find connected work<input maxLength={200} value={draft} onChange={e=>setDraft(e.target.value)}/></label><button disabled={locked}>Find work</button></form><KnowledgeStatus error={search.error} loading={search.loading}/>{!search.loading&&!search.error&&<><ul>{search.data?.data.filter(item=>item.state==='ACTIVE').map(item=><li key={item.id}>{item.title} · {item.detail} <button type="button" disabled={locked} onClick={()=>void choose(item)}>Choose {item.title}</button></li>)}</ul>{!search.data?.data.some(item=>item.state==='ACTIVE')&&<p>No active matches on this page.</p>}{search.data&&<KnowledgePager offset={page} nextOffset={search.data.nextOffset} setOffset={setPage} label="Link search pages"/>}</>}{selected&&<p>Selected: {selected.title} <button type="button" disabled={locked} onClick={()=>void mutate(selected,true)}>Confirm link</button></p>}</div>}</section>;
}
