import { z } from 'zod';
import { uuid } from './schemas';
const zone=z.string().max(64).refine(v=>{try{new Intl.DateTimeFormat('en',{timeZone:v});return true;}catch{return false;}},'Choose a valid time zone.');
export const calendarColor=z.string().regex(/^#[0-9a-fA-F]{6}$/,'Use a six-digit hex color.');
export const calendarSourceInput=z.object({name:z.string().trim().min(1).max(120),color:calendarColor.default('#315ca8'),timeZone:zone}).strict();
export const calendarSourceUpdate=z.object({version:z.number().int().min(0),name:z.string().trim().min(1).max(120).optional(),color:calendarColor.optional(),visible:z.boolean().optional(),archived:z.boolean().optional()}).strict();
export const calendarEventInput=z.object({sourceId:uuid,title:z.string().trim().min(1).max(500),description:z.string().max(20000).default(''),location:z.string().max(1000).default(''),startsAt:z.string().datetime({offset:true}),endsAt:z.string().datetime({offset:true}),timeZone:zone,isAllDay:z.boolean().default(false)}).strict().refine(v=>new Date(v.endsAt)>new Date(v.startsAt)&&new Date(v.endsAt).getTime()-new Date(v.startsAt).getTime()<=366*86400000,'End must follow start, within one year.');
export const calendarEventUpdate=z.object({version:z.number().int().positive(),event:calendarEventInput}).strict();
export const calendarCenterRange=z.object({start:z.string().datetime({offset:true}),end:z.string().datetime({offset:true}),offset:z.coerce.number().int().min(0).max(1000000).default(0),limit:z.coerce.number().int().min(1).max(200).default(100)}).strict().refine(v=>new Date(v.end)>new Date(v.start)&&new Date(v.end).getTime()-new Date(v.start).getTime()<=367*86400000,'Choose a positive range of at most one year.');
export const calendarImportInput=z.object({name:z.string().trim().min(1).max(120),color:calendarColor.default('#765096'),timeZone:zone,content:z.string().min(1).max(1000000),sourceId:uuid.optional(),version:z.number().int().positive().optional(),from:z.string().date(),through:z.string().date()}).strict().refine(v=>!!v.sourceId===!!v.version,'Re-import needs the source and its current version.');
export interface CalendarSource {id:string;name:string;kind:'INTERNAL'|'NATIVE'|'ICS'|'GOOGLE';color:string;visible:boolean;archived:boolean;timeZone:string;version:number;writable:boolean;status:string;detail:string;connectionId?:string;}
export interface CenterEvent {id:string;sourceId:string;title:string;description:string;location:string;startsAt:string;endsAt:string;timeZone:string;isAllDay:boolean;startDay:string|null;endDay:string|null;version:number;kind:'NATIVE'|'ICS'|'GOOGLE';taskId?:string|null;}
