import { randomUUID } from 'node:crypto';
import { test,expect,type Page } from '@playwright/test';
import { createDb,users,calendarConnections,calendarEvents } from '@nextdoo/db';
import { eq } from 'drizzle-orm';
const connection=createDb(process.env.DATABASE_URL!,{max:2});
test.afterAll(()=>connection.close());
const headers=()=>({Origin:'http://localhost:3100','Idempotency-Key':randomUUID()});
let ipCounter=120;
const day=()=>new Date().toISOString().slice(0,10);
async function fixture(page:Page){const email=`pc5-${randomUUID()}@test.local`;const r=await page.request.post('/api/v1/auth/register',{headers:{...headers(),'X-Forwarded-For':'198.51.100.'+ipCounter++},data:{email,password:'calendar-test-password-123',timeZone:'UTC'}});expect(r.status()).toBe(200);return {...await r.json(),email};}
async function source(page:Page){const r=await page.request.post('/api/v1/calendar/center/sources',{headers:headers(),data:{name:'Personal',timeZone:'UTC'}});expect(r.status()).toBe(200);return r.json();}
async function event(page:Page,sourceId:string,title='Appointment'){const r=await page.request.post('/api/v1/calendar/center/events',{headers:headers(),data:{sourceId,title,timeZone:'UTC',startsAt:day()+'T10:00:00Z',endsAt:day()+'T11:00:00Z'}});expect(r.status()).toBe(200);return r.json();}
const chip=(page:Page,title='Appointment')=>page.locator('.cal-native').filter({has:page.getByRole('button',{name:title,exact:true})});
const ics=(title='Imported appointment')=>`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nUID:pc5-import\r\nDTSTART:${day().replace(/-/g,'')}T120000Z\r\nDTEND:${day().replace(/-/g,'')}T130000Z\r\nSUMMARY:${title}\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`;
async function upload(page:Page,content=ics()){await page.getByRole('button',{name:'Import Calendar',exact:true}).click();await page.getByLabel('ICS file',{exact:true}).setInputFiles({name:'calendar.ics',mimeType:'text/calendar',buffer:Buffer.from(content)});await page.getByRole('button',{name:'Import snapshot',exact:true}).click();}

test('creates a calendar and an event, edits details, and deletes it',async({page})=>{
  await fixture(page);await page.goto('/calendar');await page.getByRole('button',{name:'Add Calendar',exact:true}).click();await page.getByLabel('New calendar name').fill('Home');await page.getByRole('button',{name:'Create calendar',exact:true}).click();await expect(page.getByRole('checkbox',{name:'Home',exact:true})).toBeChecked();
  await page.getByRole('button',{name:'Add event',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Event title').fill('Dentist');await dialog.getByLabel('Event start',{exact:true}).fill(day()+'T10:00');await dialog.getByLabel('Event end',{exact:true}).fill(day()+'T11:00');await dialog.getByLabel('Event location').fill('Clinic');await dialog.getByRole('button',{name:'Save event',exact:true}).click();await expect(chip(page,'Dentist')).toBeVisible();
  await chip(page,'Dentist').getByRole('button').click();await dialog.getByLabel('Event title').fill('Dentist revised');await dialog.getByLabel('Event end',{exact:true}).fill(day()+'T12:00');await dialog.getByRole('button',{name:'Save event',exact:true}).click();await expect(chip(page,'Dentist revised')).toBeVisible();await chip(page,'Dentist revised').getByRole('button').click();await expect(dialog.getByLabel('Event location')).toHaveValue('Clinic');await dialog.getByRole('button',{name:'Delete event',exact:true}).click();await expect(chip(page,'Dentist revised')).toHaveCount(0);
});

test('source visibility survives reload and agrees with Today',async({page})=>{await fixture(page);const s=await source(page);await event(page,s.id);await page.goto('/calendar');await expect(chip(page)).toBeVisible();await page.getByRole('checkbox',{name:'Personal',exact:true}).uncheck();await expect(chip(page)).toHaveCount(0);await expect(page.getByRole('checkbox',{name:'Personal',exact:true})).toBeEnabled();await page.reload();await expect(page.getByRole('checkbox',{name:'Personal',exact:true})).not.toBeChecked();await page.goto('/today');await expect(page.getByText('Appointment',{exact:true})).toHaveCount(0);await page.goto('/calendar');await page.getByRole('checkbox',{name:'Personal',exact:true}).check();await expect(chip(page)).toBeVisible();await page.goto('/today');await expect(page.getByText('Appointment',{exact:true})).toBeVisible();});

test('changes name and color and archives without deleting events',async({page})=>{await fixture(page);const s=await source(page);const e=await event(page,s.id);await page.goto('/calendar');await page.getByText('Settings for Personal',{exact:true}).click();const settings=page.locator('.calendar-source').filter({has:page.getByRole('checkbox',{name:'Personal',exact:true})});await settings.getByLabel('Calendar name',{exact:true}).fill('Family');await settings.getByLabel('Calendar color').fill('#aa2277');await settings.getByRole('button',{name:'Save calendar settings'}).click();await expect(page.getByRole('checkbox',{name:'Family',exact:true})).toBeVisible();await expect(chip(page)).toHaveCSS('border-left-color','rgb(170, 34, 119)');await page.getByRole('button',{name:'Archive calendar',exact:true}).click();await expect(chip(page)).toHaveCount(0);expect((await page.request.get('/api/v1/calendar/center/events/'+e.id)).status()).toBe(200);await page.getByRole('button',{name:'Restore calendar',exact:true}).click();await expect(chip(page)).toBeVisible();});

test('imports a read-only snapshot and identical uploads do not duplicate it',async({page})=>{await fixture(page);await page.goto('/calendar');await upload(page);await expect(chip(page,'Imported appointment')).toHaveCount(1);await chip(page,'Imported appointment').getByRole('button').click();await expect(page.getByRole('dialog')).toContainText('Read-only ics event');await expect(page.getByRole('button',{name:'Save event',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Close event'}).click();await upload(page);await expect(page.getByRole('form',{name:'Import ICS'})).toHaveCount(0);await expect(chip(page,'Imported appointment')).toHaveCount(1);expect((await (await page.request.get('/api/v1/calendar/center/sources')).json()).data.filter((s:{kind:string})=>s.kind==='ICS')).toHaveLength(1);});

test('malformed import retains the form and explains the failure',async({page})=>{await fixture(page);await page.goto('/calendar');await upload(page,'not a calendar');await expect(page.getByRole('form',{name:'Import ICS'})).toBeVisible();await expect(page.getByRole('form',{name:'Import ICS'}).getByRole('alert')).toBeVisible();expect((await (await page.request.get('/api/v1/calendar/center/sources')).json()).data.filter((s:{kind:string})=>s.kind==='ICS')).toHaveLength(0);});

test('day, week, month, year and agenda remain navigable',async({page})=>{await fixture(page);const s=await source(page);await event(page,s.id);await page.goto('/calendar');for(const view of ['Day','Week','Month','Agenda']){await page.getByRole('button',{name:view,exact:true}).click();await expect(chip(page)).toBeVisible();}await page.getByRole('button',{name:'Year',exact:true}).click();await expect(page.locator('.calendar-year > section')).toHaveCount(12);await page.getByRole('button',{name:new RegExp('^'+day()+', ')}).click();await expect(page.getByRole('button',{name:'Day',exact:true})).toHaveAttribute('aria-pressed','true');await expect(chip(page)).toBeVisible();});

test('native drag moves a day and resize changes its end',async({page})=>{await fixture(page);const s=await source(page);const e=await event(page,s.id);await page.goto('/calendar');await expect(chip(page)).toBeVisible();const cells=page.getByRole('listitem');const current=await cells.evaluateAll(nodes=>nodes.findIndex(n=>n.textContent?.includes('Appointment')));const target=(current+1)%7;await chip(page).dragTo(cells.nth(target));await expect(cells.nth(target)).toContainText('Appointment');const moved=await (await page.request.get('/api/v1/calendar/center/events/'+e.id)).json();expect(moved.startsAt).not.toBe(e.startsAt);await chip(page).getByRole('button').click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Event end',{exact:true}).fill(moved.startsAt.slice(0,10)+'T15:00');await dialog.getByRole('button',{name:'Save event',exact:true}).click();await expect(dialog).toHaveCount(0);const resized=await (await page.request.get('/api/v1/calendar/center/events/'+e.id)).json();expect(resized.endsAt).toContain('15:00:00');});

test('all-day event spans the intended dates with an exclusive end',async({page})=>{await fixture(page);await source(page);await page.goto('/calendar');await page.getByRole('button',{name:'Add event',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Event title').fill('Day off');await dialog.getByLabel('All-day',{exact:true}).check();await dialog.getByLabel('Event start',{exact:true}).fill(day());const tomorrow=new Date(Date.now()+86400000).toISOString().slice(0,10);await dialog.getByLabel('Event end (exclusive date)').fill(tomorrow);await dialog.getByRole('button',{name:'Save event',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(chip(page,'Day off')).toHaveCount(1);await expect(chip(page,'Day off')).toContainText('All day');});

test('Google mirror fixture has separate persisted visibility and stays read-only',async({page})=>{const f=await fixture(page);const [u]=await connection.db.select().from(users).where(eq(users.email,f.email));const id=randomUUID();await connection.db.insert(calendarConnections).values({id,userId:u!.id,workspaceId:f.workspaceId,provider:'google',status:'ACTIVE',mode:'READ_ONLY',externalAccountId:'fixture@example.test',accessTokenEncrypted:'fixture-only'});await connection.db.insert(calendarEvents).values({id:randomUUID(),workspaceId:f.workspaceId,connectionId:id,calendarId:'primary',externalId:'fixture-event',title:'Google fixture',startsAt:new Date(day()+'T14:00:00Z'),endsAt:new Date(day()+'T15:00:00Z')});await page.goto('/calendar');await expect(page.getByRole('button',{name:'Google fixture',exact:true})).toBeVisible();await page.getByRole('checkbox',{name:'Google · Primary',exact:true}).uncheck();await expect(page.getByRole('button',{name:'Google fixture',exact:true})).toHaveCount(0);await expect(page.getByRole('checkbox',{name:'Google · Primary',exact:true})).toBeEnabled();await page.reload();await expect(page.getByRole('checkbox',{name:'Google · Primary',exact:true})).not.toBeChecked();await page.getByRole('checkbox',{name:'Google · Primary',exact:true}).check();await page.getByRole('button',{name:'Google fixture',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Read-only google event');});

test('mobile calendar allows event editing without page overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await fixture(page);const s=await source(page);await event(page,s.id);await page.goto('/calendar');await page.getByRole('button',{name:'Agenda',exact:true}).click();await chip(page).getByRole('button').click();await expect(page.getByRole('dialog').getByLabel('Event title')).toHaveValue('Appointment');await page.getByRole('button',{name:'Close event'}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);await page.screenshot({path:'test-results/calendar-center-mobile.png',fullPage:true});});

test('failed visibility save restores the checked source and keeps the event',async({page})=>{await fixture(page);const s=await source(page);await event(page,s.id);await page.goto('/calendar');await expect(chip(page)).toBeVisible();await page.route('**/api/v1/calendar/center/sources/'+s.id,route=>route.fulfill({status:503,contentType:'application/problem+json',body:JSON.stringify({title:'Temporarily unavailable',detail:'Try again later.',status:503})}));await page.getByRole('checkbox',{name:'Personal',exact:true}).click();await expect(page.getByRole('checkbox',{name:'Personal',exact:true})).toBeChecked();await expect(chip(page)).toBeVisible();await expect(page.getByRole('complementary',{name:'Calendars'}).getByRole('alert')).toHaveText('Try again later.');});

test('uses the workspace clock in the grid and the event clock in its editor',async({page})=>{await fixture(page);const s=await source(page);const r=await page.request.post('/api/v1/calendar/center/events',{headers:headers(),data:{sourceId:s.id,title:'Cross zone',timeZone:'Asia/Kolkata',startsAt:day()+'T10:00:00Z',endsAt:day()+'T11:00:00Z'}});expect(r.status()).toBe(200);await page.goto('/calendar');await expect(chip(page,'Cross zone')).toContainText(/10:00/);await chip(page,'Cross zone').getByRole('button').click();await expect(page.getByRole('dialog').getByLabel('Event start',{exact:true})).toHaveValue(day()+'T15:30');await expect(page.getByRole('dialog').getByLabel('Event time zone')).toHaveValue('Asia/Kolkata');});

test('cross-zone drag lands on the selected workspace day',async({page})=>{await fixture(page);const s=await source(page);const r=await page.request.post('/api/v1/calendar/center/events',{headers:headers(),data:{sourceId:s.id,title:'Late event',timeZone:'Asia/Kolkata',startsAt:day()+'T22:00:00Z',endsAt:day()+'T23:00:00Z'}});expect(r.status()).toBe(200);const e=await r.json();await page.goto('/calendar');await expect(chip(page,'Late event')).toBeVisible();const cells=page.getByRole('listitem'),current=await cells.evaluateAll(nodes=>nodes.findIndex(n=>n.textContent?.includes('Late event'))),target=(current+1)%7;await chip(page,'Late event').dragTo(cells.nth(target));await expect(cells.nth(target)).toContainText('Late event');const moved=await (await page.request.get('/api/v1/calendar/center/events/'+e.id)).json();expect(moved.startsAt).toContain('T22:00:00');});

test('re-import updates the same snapshot while retaining its name and color',async({page})=>{await fixture(page);const r=await page.request.post('/api/v1/calendar/center/import',{headers:headers(),data:{name:'College',color:'#aa2277',timeZone:'UTC',content:ics(),from:day().slice(0,4)+'-01-01',through:String(Number(day().slice(0,4))+1)+'-01-01'}});expect(r.status()).toBe(200);const imported=await r.json();await page.goto('/calendar');await expect(chip(page,'Imported appointment')).toBeVisible();await page.getByRole('button',{name:'Import Calendar',exact:true}).click();await page.getByRole('combobox',{name:/Destination/}).selectOption(imported.source.id);await expect(page.getByLabel('Import name',{exact:true})).toHaveValue('College');await page.getByLabel('ICS file',{exact:true}).setInputFiles({name:'updated.ics',mimeType:'text/calendar',buffer:Buffer.from(ics('Updated lecture'))});await page.getByRole('button',{name:'Import snapshot',exact:true}).click();await expect(chip(page,'Updated lecture')).toHaveCSS('border-left-color','rgb(170, 34, 119)');await expect(chip(page,'Imported appointment')).toHaveCount(0);await expect(page.getByRole('checkbox',{name:'College',exact:true})).toBeChecked();});
