import { randomUUID } from 'node:crypto';
import { test,expect,type Page } from '@playwright/test';
import { createTrackerDefinition } from '@nextdoo/core';
let ip=10;
const headers=()=>({Origin:'http://localhost:3100','Idempotency-Key':randomUUID()});
const today=()=>new Date().toISOString().slice(0,10);
async function fixture(page:Page){const r=await page.request.post('/api/v1/auth/register',{headers:{...headers(),'X-Forwarded-For':`203.0.113.${ip++}`},data:{email:`pc6-${randomUUID()}@test.local`,password:'insights-test-password-123',timeZone:'UTC'}});expect(r.status()).toBe(200);return r.json();}
async function post(page:Page,path:string,data:unknown){const r=await page.request.post('/api/v1/'+path,{headers:headers(),data});expect(r.status(),await r.text()).toBe(200);return r.json();}
const metric=(page:Page,label:string)=>page.locator('dl > div').filter({has:page.getByText(label,{exact:true})}).locator('dd');
test('opens Insights from navigation with honest empty metrics',async({page})=>{await fixture(page);await page.goto('/today');await page.getByRole('link',{name:'Insights',exact:true}).click();await expect(page.getByRole('heading',{name:'Insights',exact:true})).toBeVisible();await expect(page.getByText('No activity to summarize yet.',{exact:false})).toBeVisible();await expect(metric(page,'Completion rate')).toHaveText('Not available');});
test('changes every period and validates a custom range',async({page})=>{await fixture(page);await page.goto('/insights');for(const period of ['day','week','quarter','year','month']){await page.getByLabel('Period',{exact:true}).selectOption(period);await expect(page.locator('.insights-period')).toContainText('UTC');await expect(page.getByText('Loading Insights…')).toHaveCount(0);}await page.getByLabel('Period',{exact:true}).selectOption('custom');await expect(page.locator('.insights-view').getByRole('status')).toContainText('Choose both dates');await page.getByLabel('From',{exact:true}).fill('2026-09-01');await page.getByLabel('Through',{exact:true}).fill('2026-09-03');await expect(page.locator('.insights-period')).toHaveText('2026-09-01 – 2026-09-03 · UTC');});
test('shows task activity, due cohort and accessible daily breakdown',async({page})=>{const f=await fixture(page),t=await post(page,'tasks',{workspaceId:f.workspaceId,title:'Read book',dueAt:today()+'T12:00:00Z'});await post(page,`tasks/${t.id}/complete`,{version:t.version});await page.goto('/insights?period=day');await expect(metric(page,'Tasks completed')).toHaveText('1');await expect(metric(page,'Tasks created')).toHaveText('1');await expect(metric(page,'Completion rate')).toHaveText('100%');await page.getByText('Task daily trend and breakdowns',{exact:true}).click();await expect(page.getByRole('table',{name:'Task daily trend',exact:true})).toBeVisible();});
test('shows Goal Center progress and links to the original goal',async({page})=>{const f=await fixture(page),g=await post(page,'goals',{workspaceId:f.workspaceId,title:'Learn Spanish'});await page.goto('/insights');await expect(metric(page,'Active goals now')).toHaveText('1');await expect(page.getByText('No measurable units')).toBeVisible();await page.getByRole('link',{name:'Learn Spanish',exact:true}).click();await expect(page).toHaveURL(new RegExp('/goals/'+g.id));});
test('shows saved tracker scores and recording streaks',async({page})=>{const f=await fixture(page),t=await post(page,'trackers',{workspaceId:f.workspaceId,name:'Reading',startDate:today(),timeZone:'UTC',definition:createTrackerDefinition()});await post(page,`trackers/${t.id}/entries`,{day:today(),values:{input:90}});await page.goto('/insights?period=day');await expect(metric(page,'Total stars')).toHaveText('5');await expect(metric(page,'Tracked days')).toHaveText('1');await expect(page.getByRole('table',{name:'Tracker comparison',exact:true})).toContainText('Reading');await expect(page.getByRole('columnheader',{name:'Longest streak'})).toBeVisible();});
test('shows Calendar workload without leaking event details',async({page})=>{await fixture(page);const s=await post(page,'calendar/center/sources',{name:'Personal',timeZone:'UTC'});await post(page,'calendar/center/events',{sourceId:s.id,title:'Private appointment',timeZone:'UTC',startsAt:today()+'T10:00:00Z',endsAt:today()+'T11:30:00Z'});await page.goto('/insights?period=day');await expect(metric(page,'Scheduled events')).toHaveText('1');await expect(metric(page,'Scheduled minutes')).toHaveText('90');await expect(page.getByText('Private appointment')).toHaveCount(0);});
test('opens a report preserving dates, exports both formats, and exposes print',async({page})=>{await fixture(page);await page.goto('/insights?period=custom&from=2026-09-01&to=2026-09-03');await page.getByRole('link',{name:'Open report',exact:true}).click();await expect(page.getByRole('heading',{name:'Insights report',exact:true})).toBeVisible();await expect(page.locator('.insights-period')).toHaveText('2026-09-01 – 2026-09-03 · UTC');for(const format of ['CSV','JSON']){const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download '+format}).click();expect((await download).suggestedFilename()).toBe('nextdoo-insights-2026-09-01-2026-09-03.'+format.toLowerCase());}await expect(page.getByRole('button',{name:'Print report'})).toBeVisible();});
test('mobile report has no horizontal page overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await fixture(page);await page.goto('/insights/reports?period=week');await expect(metric(page,'Tasks completed')).toHaveText('0');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);const {default:AxeBuilder}=await import('@axe-core/playwright');expect((await new AxeBuilder({page}).include('.insights-view').withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations).toEqual([]);await page.screenshot({path:'test-results/insights-mobile.png',fullPage:true});});
test('offers comparison settings and removes hidden scores and streaks',async({page})=>{await fixture(page);await page.goto('/insights?period=custom&from=2026-09-01&to=2026-09-03&compare=true');await expect(page.getByText('Period comparisons are hidden in Wellbeing settings.',{exact:false})).toBeVisible();await page.goto('/settings?section=all');await page.getByRole('checkbox',{name:'Hide numeric scores'}).check();await expect(page.getByRole('checkbox',{name:'Hide tracker streaks'})).toBeEnabled();await page.getByRole('checkbox',{name:'Hide tracker streaks'}).check();await expect(page.getByRole('checkbox',{name:'Hide period comparisons'})).toBeEnabled();await page.getByRole('checkbox',{name:'Hide period comparisons'}).uncheck();await expect(page.getByRole('checkbox',{name:'Hide numeric scores'})).toBeEnabled();await page.goto('/insights?period=custom&from=2026-09-01&to=2026-09-03&compare=true');await expect(metric(page,'Completed tasks change')).toHaveText('0');await expect(page.getByText('Numeric scores are hidden in Wellbeing settings.')).toBeVisible();await expect(page.getByRole('columnheader',{name:'Longest streak'})).toHaveCount(0);});
test('shows server errors without stale or fabricated metrics',async({page})=>{await fixture(page);await page.route('**/api/v1/insights?*',route=>route.fulfill({status:503,contentType:'application/problem+json',body:JSON.stringify({detail:'Please retry later.'})}));await page.goto('/insights');await expect(page.locator('.insights-view').getByRole('alert')).toHaveText('Please retry later.');await expect(metric(page,'Tasks completed')).toHaveCount(0);});
test('requires authentication and rejects foreign workspace query parameters',async({page})=>{expect((await page.request.get('/api/v1/insights')).status()).toBe(401);expect((await page.request.get('/api/v1/insights/export?format=json')).status()).toBe(401);await fixture(page);expect((await page.request.get('/api/v1/insights?workspaceId='+randomUUID())).status()).toBe(400);const r=await page.request.get('/api/v1/insights');expect(r.status()).toBe(200);expect(r.headers()['cache-control']).toContain('no-store');});
