import { randomUUID } from 'node:crypto';
import { expect,test,type Page } from '@playwright/test';
import { createTrackerDefinition } from '@nextdoo/core';
const origin={Origin:'http://localhost:3100'},headers=()=>({...origin,'Idempotency-Key':randomUUID()});
async function fixture(page:Page){const r=await page.request.post('/api/v1/auth/register',{headers:{...origin,'X-Forwarded-For':`198.51.100.${100+Math.floor(Math.random()*100)}`},data:{email:`knowledge-${randomUUID()}@test.local`,password:'knowledge-test-password-123',timeZone:'UTC'}});expect(r.status()).toBe(200);return await r.json();}
async function database(page:Page){const r=await page.request.post('/api/v1/knowledge/databases',{headers:headers(),data:{name:'My library',templateId:'books'}});expect(r.status()).toBe(200);return await r.json();}
async function record(page:Page,id:string,title='A reference'){const r=await page.request.post(`/api/v1/knowledge/databases/${id}/records`,{headers:headers(),data:{title,content:'**Useful** content'}});expect(r.status()).toBe(200);return await r.json();}

test('creates a blank database, adds properties and persists a typed record',async({page})=>{
  await fixture(page);await page.goto('/knowledge');await page.getByLabel('Database name',{exact:true}).fill('Research library');await page.getByRole('button',{name:'Create database',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Research library',exact:true})).toBeVisible();await page.getByText('Database settings and properties',{exact:true}).click();
  const form=page.getByRole('form',{name:'Add property',exact:true});await form.getByLabel('Property name').fill('Score');await form.getByLabel('Property type').selectOption('NUMBER');await form.getByRole('button',{name:'Add property',exact:true}).click();
  await expect(page.getByRole('columnheader',{name:'Score',exact:true})).toBeVisible();await page.getByRole('button',{name:'New record',exact:true}).click();const create=page.getByRole('form',{name:'New record',exact:true});await create.getByLabel('Title',{exact:true}).fill('First record');await create.getByLabel('Score',{exact:true}).fill('4.5');await create.getByRole('button',{name:'Add record',exact:true}).click();
  await expect(page.getByRole('link',{name:'First record',exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('cell',{name:'4.5',exact:true})).toBeVisible();
});
test('previews a template and creates independent database properties',async({page})=>{
  await fixture(page);await page.goto('/knowledge');await page.getByLabel('Database name').fill('My books');await page.getByLabel('Starting template').selectOption('books');await page.getByRole('button',{name:'Preview template'}).click();await expect(page.getByRole('article',{name:'Template preview'})).toContainText('Author');await page.getByRole('button',{name:'Create database',exact:true}).click();await expect(page.getByRole('columnheader',{name:'Author',exact:true})).toBeVisible();
  const other=await database(page);expect(other.properties).toHaveLength(5);
});
test('filters numeric values, sorts and switches bounded views',async({page})=>{
  await fixture(page);const d=await database(page),pages=d.properties.find((p:{name:string})=>p.name==='Pages').id;
  for(const [title,n] of [['Short',12],['Long',400],['Medium',150]]){const r=await page.request.post(`/api/v1/knowledge/databases/${d.id}/records`,{headers:headers(),data:{title,values:{[pages]:n}}});expect(r.status()).toBe(200);}
  await page.goto(`/knowledge/databases/${d.id}`);await page.getByLabel('Filter property').selectOption(pages);await page.getByLabel('Filter condition').selectOption('gte');await page.getByLabel('Filter value',{exact:true}).fill('100');await page.getByRole('button',{name:'Apply filters'}).click();await expect(page.getByRole('table').getByRole('row')).toHaveCount(3);await expect(page.getByRole('link',{name:'Short',exact:true})).toHaveCount(0);await page.getByLabel('Sort by').selectOption(pages);await page.getByLabel('Direction',{exact:true}).selectOption('asc');await expect(page.getByRole('table').getByRole('row').nth(1)).toContainText('Medium');
  for(const view of ['list','gallery','board']){await page.getByLabel('View',{exact:true}).selectOption(view);await expect(page.getByRole('link',{name:'Long',exact:true})).toBeVisible();}
});
test('edits, duplicates, deletes and restores record content',async({page})=>{
  await fixture(page);const d=await database(page),r=await record(page,d.id);await page.goto(`/knowledge/records/${r.id}`);await page.getByRole('button',{name:'Edit record',exact:true}).click();const form=page.getByRole('form',{name:'Edit record',exact:true});await form.getByLabel('Title',{exact:true}).fill('Updated reference');await form.getByLabel('Record content (Markdown)').fill('## My findings\n\nSafe **rich content**');await form.getByRole('button',{name:'Save record'}).click();await expect(page.getByRole('heading',{name:'My findings'})).toBeVisible();await page.getByRole('button',{name:'Delete record',exact:true}).click();await expect(page.getByRole('button',{name:'Restore record',exact:true})).toBeVisible();await page.getByRole('button',{name:'Restore record',exact:true}).click();await page.getByRole('button',{name:'Duplicate record',exact:true}).click();await expect(page.getByRole('heading',{name:'Updated reference (copy)',exact:true})).toBeVisible();
});
test('creates a record note with safe rich content and parent navigation',async({page})=>{
  await fixture(page);const d=await database(page),r=await record(page,d.id);await page.goto(`/knowledge/records/${r.id}`);await page.getByRole('link',{name:'Add record note',exact:true}).click();await page.getByLabel('Note title').fill('Study note');await page.getByLabel('Note content (Markdown)').fill('### Key idea\n\n[Source](https://example.org)');await page.getByRole('button',{name:'Preview content'}).click();await expect(page.getByRole('heading',{name:'Key idea'})).toBeVisible();await page.getByRole('button',{name:'Create note',exact:true}).click();await expect(page.getByRole('heading',{name:'Study note',exact:true})).toBeVisible();await page.getByRole('link',{name:'Parent record'}).click();await expect(page.getByRole('link',{name:'Study note',exact:true})).toBeVisible();
});
test('links a record to Tasks, Goals and Tracker and exposes backlinks',async({page})=>{
  const {workspaceId}=await fixture(page),d=await database(page),r=await record(page,d.id);
  const task=await (await page.request.post('/api/v1/tasks',{headers:headers(),data:{workspaceId,title:'Read research'}})).json();
  const goal=await (await page.request.post('/api/v1/goals',{headers:headers(),data:{workspaceId,title:'Learn science'}})).json();
  const tracker=await (await page.request.post('/api/v1/trackers',{headers:headers(),data:{workspaceId,name:'Reading tracker',startDate:'2026-01-01',timeZone:'UTC',definition:createTrackerDefinition()}})).json();
  await page.goto(`/knowledge/records/${r.id}`);const relations=page.getByRole('region',{name:'Relations',exact:true});
  for(const [kind,title] of [['task','Read research'],['goal','Learn science'],['tracker','Reading tracker']]){await relations.getByLabel('Item type').selectOption(kind!);await relations.getByLabel('Find an item').fill(title!);await relations.getByRole('button',{name:'Search items'}).click();await relations.getByRole('button',{name:`Link ${title}`,exact:true}).click();await expect(relations.getByRole('button',{name:`Unlink ${title}`,exact:true})).toBeVisible();}
  expect((await (await page.request.get(`/api/v1/knowledge/backlinks?kind=task&id=${task.id}`)).json()).data).toHaveLength(1);
  await page.goto(`/goals/${goal.id}`);await expect(page.getByRole('region',{name:'Knowledge references'}).getByRole('link',{name:'A reference'})).toBeVisible();await page.goto(`/trackers/${tracker.id}`);await expect(page.getByRole('region',{name:'Knowledge references'}).getByRole('link',{name:'A reference'})).toBeVisible();
});
test('exports only the displayed page and remains usable on mobile',async({page})=>{
  await fixture(page);const d=await database(page);await record(page,d.id);await page.setViewportSize({width:390,height:844});await page.goto(`/knowledge/databases/${d.id}`);await expect(page.getByRole('link',{name:'A reference',exact:true})).toBeVisible();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export this page as CSV'}).click();expect((await download).suggestedFilename()).toBe('knowledge-page-1.csv');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:test.info().outputPath('knowledge-mobile.png'),fullPage:true});
});
test('enforces authentication, tenant isolation and replay-safe creation at the API',async({page,browser})=>{
  await fixture(page);const d=await database(page),r=await record(page,d.id);const context=await browser.newContext(),other=await context.newPage();expect((await other.request.get(`/api/v1/knowledge/records/${r.id}`)).status()).toBe(401);await fixture(other);expect((await other.request.get(`/api/v1/knowledge/records/${r.id}`)).status()).toBe(404);expect((await other.request.patch(`/api/v1/knowledge/databases/${d.id}`,{headers:headers(),data:{version:1,name:'Stolen'}})).status()).toBe(404);const h=headers(),data={title:'Only once'};const a=await page.request.post(`/api/v1/knowledge/databases/${d.id}/records`,{headers:h,data}),b=await page.request.post(`/api/v1/knowledge/databases/${d.id}/records`,{headers:h,data});expect((await a.json()).id).toBe((await b.json()).id);await context.close();
});
test('keeps a stale draft and reports conflicts instead of overwriting',async({page})=>{
  await fixture(page);const d=await database(page),r=await record(page,d.id);await page.goto(`/knowledge/records/${r.id}`);await page.getByRole('button',{name:'Edit record',exact:true}).click();await page.getByRole('form',{name:'Edit record'}).getByLabel('Title',{exact:true}).fill('My draft');expect((await page.request.patch(`/api/v1/knowledge/records/${r.id}`,{headers:headers(),data:{version:1,title:'Other device',content:'changed',values:{}}})).status()).toBe(200);await page.getByRole('button',{name:'Save record'}).click();await expect(page.getByRole('form',{name:'Edit record'}).getByRole('alert')).toContainText('changed elsewhere');await expect(page.getByRole('form',{name:'Edit record'}).getByLabel('Title',{exact:true})).toHaveValue('My draft');await page.getByRole('button',{name:'Reload saved version'}).click();await expect(page.getByRole('form',{name:'Edit record'}).getByLabel('Title',{exact:true})).toHaveValue('Other device');
});
