import { randomUUID } from 'node:crypto';
import { test,expect,type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { createTrackerDefinition } from '@nextdoo/core';
const headers=()=>({Origin:'http://localhost:3100','Idempotency-Key':randomUUID()});
let address=210;
async function post(page:Page,path:string,data:object){const r=await page.request.post('/api/v1'+path,{headers:headers(),data});expect(r.status(),await r.text()).toBe(200);return r.json();}
async function setup(page:Page){const r=await page.request.post('/api/v1/auth/register',{headers:{...headers(),'X-Forwarded-For':`192.0.2.${address++}`},data:{email:`shared-${randomUUID()}@test.local`,password:'shared-workspace-test-password',timeZone:'UTC'}});expect(r.ok()).toBe(true);return r.json();}

test('palette supports keyboard, focus return, mobile accessibility and real task discovery',async({page})=>{
 const {workspaceId}=await setup(page),task=await post(page,'/tasks',{workspaceId,title:'Workspace keyboard task'});await page.goto('/home');const launcher=page.getByRole('button',{name:'Commands',exact:true});await launcher.focus();await page.keyboard.press('?');const dialog=page.getByRole('dialog',{name:'Commands',exact:true});await expect(dialog).toBeVisible();await expect(dialog.getByLabel('Find a command or item')).toBeFocused();await page.keyboard.press('ArrowDown');await expect(dialog.getByRole('link',{name:'Create a task',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(launcher).toBeFocused();
 await launcher.click();await dialog.getByRole('button',{name:'Close commands',exact:true}).focus();await page.keyboard.press('Shift+Tab');await expect(dialog.getByRole('link',{name:'Open Notifications',exact:true})).toBeFocused();await page.keyboard.press('Tab');await expect(dialog.getByRole('button',{name:'Close commands',exact:true})).toBeFocused();await page.setViewportSize({width:390,height:844});expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/shared-palette-mobile.png'});await dialog.getByLabel('Find a command or item').fill('Workspace keyboard');await expect(dialog.getByRole('link',{name:'Workspace keyboard task',exact:true})).toBeVisible();await dialog.getByRole('link',{name:'Workspace keyboard task',exact:true}).focus();await page.keyboard.press('Enter');await expect(page).toHaveURL(`/tasks/${task.id}`);await page.goto('/search');await page.getByLabel('Result type').selectOption('calendar');await page.getByRole('button',{name:'Commands',exact:true}).click();await dialog.getByLabel('Find a command or item').fill('Workspace keyboard');await dialog.getByRole('link',{name:'See all search results',exact:true}).click();await expect(page.getByLabel('Result type')).toHaveValue('all');await expect(page.getByRole('link',{name:'Workspace keyboard task',exact:true})).toBeVisible();
});
test('palette creates through existing capture and does not intercept typing',async({page})=>{
 await setup(page);await page.goto('/home');await page.getByRole('button',{name:'Commands',exact:true}).click();await page.getByRole('dialog',{name:'Commands',exact:true}).getByRole('link',{name:'Create a task',exact:true}).click();await expect(page).toHaveURL(/inbox#capture$/);await expect(page.locator('#capture')).toBeFocused();await page.locator('#capture').fill('A question?');await page.keyboard.press('?');await expect(page.getByRole('dialog',{name:'Commands',exact:true})).toHaveCount(0);await page.locator('#capture').fill('Captured from workspace');await page.locator('#capture').press('Enter');await expect(page.getByRole('button',{name:'Edit "Captured from workspace"',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Commands',exact:true}).click();await page.getByRole('dialog',{name:'Commands',exact:true}).getByRole('link',{name:'Start Focus',exact:true}).click();await expect(page).toHaveURL('/focus');
});
test('task-side linking reuses Goal, Milestone and Tracker and exposes reminder navigation',async({page})=>{
 const {workspaceId}=await setup(page),task=await post(page,'/tasks',{workspaceId,title:'Linked workspace task'}),goal=await post(page,'/goals',{workspaceId,title:'Workspace goal'}),milestone=await post(page,`/goals/${goal.id}/milestones`,{title:'Workspace milestone'}),tracker=await post(page,'/trackers',{workspaceId,name:'Workspace tracker',timeZone:'UTC',startDate:'2026-01-01',definition:createTrackerDefinition()});await page.goto('/tasks/'+task.id);const region=page.getByRole('region',{name:'Connected work',exact:true});
 for(const [kind,name] of [['milestone','Workspace milestone'],['goal','Workspace goal'],['tracker','Workspace tracker']]){await region.getByRole('button',{name:'Link existing work',exact:true}).click();await region.getByLabel('Link type').selectOption(kind!);await region.getByRole('button',{name:'Choose '+name,exact:true}).click();await region.getByRole('button',{name:'Confirm link',exact:true}).click();await expect(region.getByRole('button',{name:'Unlink '+name,exact:true})).toBeVisible();}
 await region.getByRole('button',{name:'Unlink Workspace goal',exact:true}).click();await expect(region.getByRole('button',{name:'Unlink Workspace goal',exact:true})).toHaveCount(0);await expect(region.getByRole('link',{name:'Workspace goal',exact:true})).toBeVisible();await region.getByRole('button',{name:'Unlink Workspace milestone',exact:true}).click();await expect(region.getByRole('link',{name:'Workspace goal',exact:true})).toHaveCount(0);await region.getByRole('button',{name:'Unlink Workspace tracker',exact:true}).click();await expect(region.getByText('No linked goals or trackers.')).toBeVisible();await region.getByRole('link',{name:'Task reminders',exact:true}).click();await expect(page).toHaveURL(`/notifications?taskId=${task.id}`);await expect(page.getByRole("heading",{name:"Notifications",exact:true})).toBeVisible();await expect(page.getByRole("heading",{name:"Reminders for Linked workspace task",exact:true})).toBeVisible();await expect(page.getByText("No reminders scheduled.", {exact:true})).toBeVisible();expect((await page.request.get(`/api/v1/trackers/${tracker.id}`)).ok()).toBe(true);expect((await page.request.get(`/api/v1/milestones/${milestone.id}`)).ok()).toBe(true);
});
test('retains a stale relationship selection for explicit reload and replays one command',async({page,browser})=>{
 const {workspaceId}=await setup(page),task=await post(page,'/tasks',{workspaceId,title:'Conflict task'}),goal=await post(page,'/goals',{workspaceId,title:'Conflict goal'});await page.goto('/tasks/'+task.id);const region=page.getByRole('region',{name:'Connected work',exact:true});await region.getByRole('button',{name:'Link existing work',exact:true}).click();await region.getByRole('button',{name:'Choose Conflict goal',exact:true}).click();expect((await page.request.patch('/api/v1/goals/'+goal.id,{headers:headers(),data:{version:1,title:'Changed goal'}})).ok()).toBe(true);await region.getByRole('button',{name:'Confirm link',exact:true}).click();await expect(region.getByRole('alert')).toContainText('changed elsewhere');await region.getByRole('button',{name:'Reload saved version',exact:true}).click();await region.getByRole('button',{name:'Confirm link',exact:true}).click();await expect(region.getByRole('link',{name:'Changed goal',exact:true})).toBeVisible();
 const h=headers(),data={version:3,taskId:task.id,linked:false},first=await page.request.post(`/api/v1/goals/${goal.id}/tasks`,{headers:h,data}),replay=await page.request.post(`/api/v1/goals/${goal.id}/tasks`,{headers:h,data});expect(first.status()).toBe(200);expect(await replay.json()).toEqual(await first.json());const other=await browser.newContext(),p=await other.newPage();expect((await p.request.get('/api/v1/connected/search')).status()).toBe(401);await setup(p);expect((await p.request.post(`/api/v1/goals/${goal.id}/tasks`,{headers:headers(),data:{version:4,taskId:task.id,linked:true}})).status()).toBe(404);await other.close();
});
test('shared tags find Tasks and Notes and project-list results open filtered tasks',async({page})=>{
 const {workspaceId}=await setup(page),tag=await post(page,'/tags',{workspaceId,name:'Review'}),project=await post(page,'/projects',{workspaceId,name:'Workspace project'}),section=await post(page,'/sections',{projectId:project.id,name:'Workspace list'}),task=await post(page,'/tasks',{workspaceId,title:'Tagged workspace task',tagIds:[tag.id],projectId:project.id,sectionId:section.id}),note=await post(page,'/knowledge/notes',{title:'Tagged workspace note',tagIds:[tag.id]});await post(page,'/tasks',{workspaceId,title:'Unfiled unrelated task'});await post(page,'/tasks',{workspaceId,projectId:project.id,title:'Other list task'});
 await page.goto('/knowledge/notes/'+note.id);await page.getByRole('link',{name:'#review',exact:true}).click();await expect(page.getByRole('link',{name:'Tagged workspace task',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Tagged workspace note',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Unfiled unrelated task',exact:true})).toHaveCount(0);await page.getByLabel('Shared tag').selectOption('');await page.getByLabel('Result type').selectOption('list');await page.getByRole('link',{name:'Workspace list',exact:true}).click();await expect(page.getByLabel('Project',{exact:true})).toHaveValue(project.id);await expect(page.getByLabel('Project list',{exact:true})).toHaveValue(section.id);await expect(page.locator(`[data-task-id="${task.id}"]`)).toBeVisible();await expect(page.getByRole('button',{name:'Edit "Unfiled unrelated task"',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Edit "Other list task"',exact:true})).toHaveCount(0);
});
test('Home and search open exact Calendar events with versioned Knowledge round trips',async({page,browser})=>{
 await setup(page);const source=await post(page,'/calendar/center/sources',{name:'Personal',timeZone:'UTC'}),day=new Date().toISOString().slice(0,10),event=await post(page,'/calendar/center/events',{sourceId:source.id,title:'Workspace meeting',startsAt:day+'T12:00:00Z',endsAt:day+'T13:00:00Z',timeZone:'UTC'}),note=await post(page,'/knowledge/notes',{title:'Workspace meeting notes'});
 await page.goto('/home');await page.getByRole('region',{name:'Calendar',exact:true}).getByRole('link',{name:'Workspace meeting',exact:true}).click();await expect(page).toHaveURL('/calendar/events/'+event.id);const refs=page.getByRole('region',{name:'Knowledge references',exact:true});await refs.getByRole('button',{name:'Link Knowledge',exact:true}).click();await refs.getByLabel('Knowledge type').selectOption('note');await refs.getByRole('button',{name:'Link reference Workspace meeting notes',exact:true}).click();await refs.getByRole('link',{name:'Workspace meeting notes',exact:true}).click();await expect(page).toHaveURL('/knowledge/notes/'+note.id);await page.getByRole('region',{name:'Relations',exact:true}).getByRole('link',{name:'Workspace meeting',exact:true}).click();await expect(page).toHaveURL('/calendar/events/'+event.id);
 await page.goto('/search');await page.getByLabel('Result type').selectOption('calendar');await page.getByRole('link',{name:'Workspace meeting',exact:true}).click();await expect(page).toHaveURL('/calendar/events/'+event.id);const other=await browser.newContext(),p=await other.newPage();await setup(p);expect((await p.request.get('/api/v1/calendar/center/events/'+event.id)).status()).toBe(404);await other.close();expect((await page.request.delete('/api/v1/calendar/center/events/'+event.id,{headers:headers(),data:{version:1}})).ok()).toBe(true);await page.goto('/knowledge/notes/'+note.id);await expect(page.getByRole('region',{name:'Relations',exact:true})).toContainText('Unavailable Calendar event');await page.getByRole('button',{name:'Unlink Unavailable Calendar event',exact:true}).click();await expect(page.getByRole('region',{name:'Relations',exact:true})).not.toContainText('Unavailable Calendar event');
});
test('palette keeps navigation usable offline and reports search failure without invented results',async({page,context})=>{
 await setup(page);await page.goto('/home');await context.setOffline(true);await page.getByRole('button',{name:'Commands',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Commands',exact:true});await dialog.getByLabel('Find a command or item').fill('No invented items');await expect(dialog.getByRole('status')).toContainText('Requires connection');await expect(dialog.getByRole('link',{name:'See all search results',exact:true})).toBeVisible();await dialog.getByLabel('Find a command or item').fill('');await expect(dialog.getByRole('link',{name:'Open Home',exact:true})).toBeVisible();await page.keyboard.press('Escape');await context.setOffline(false);
});
