import { randomUUID } from 'node:crypto';
import { expect, it } from 'vitest';
import { eq } from 'drizzle-orm';
import { knowledgeRecords, knowledgeValues, knowledgeRelations, auditLogs, syncChanges, purgeAccount, users, tags } from '@nextdoo/db';
import { requireTestDatabase } from '../../../../../tests/database';
import { getDb } from '../db';
import { registerUser } from './accounts';
import { createTask } from './tasks';
import { createGoal } from './goals';
import { buildExport } from './data-rights';
import * as k from './knowledge';
import * as q from './knowledge-query';
import * as r from './knowledge-relations';

await requireTestDatabase();
async function fixture() {
  const user=await registerUser({email:`knowledge-${randomUUID()}@test.local`,passwordHash:'test',name:null,timeZone:'UTC'});
  const actor={userId:user.id,workspaceId:user.workspaceId};
  const database=await k.createKnowledgeDatabase(actor,{name:'Library',properties:[{name:'Title',type:'TITLE'},{name:'Pages',type:'NUMBER'},{name:'Read',type:'CHECKBOX'},{name:'Status',type:'SELECT',config:{options:['Next','Done']}},{name:'Topics',type:'MULTI_SELECT',config:{options:['Science','Art']}},{name:'Date',type:'DATE'},{name:'Summary',type:'RICH_TEXT'},{name:'Related',type:'RELATION'},{name:'Files',type:'FILE'}]});
  const ids=Object.fromEntries(database.properties.map(p=>[p.name,p.id]));
  return {actor,database,ids};
}
it('stores typed values, searches text, and filters/sorts/pages on the server',async()=>{
  const {actor,database,ids}=await fixture();
  for(let i=0;i<5;i++) await k.createKnowledgeRecord(actor,database.id,{title:`Book ${i}`,values:{[ids.Pages!]:i,[ids.Read!]:false,[ids.Status!]:'Next',[ids.Topics!]:['Science'],[ids.Date!]:'2026-09-23',[ids.Summary!]:'A **quantum** reference'}});
  const page=await q.knowledgeRecordPage(actor.workspaceId,database.id,{q:'quantum',filters:[{propertyId:ids.Pages,operator:'gte',value:2}],sort:ids.Pages,direction:'asc',limit:2});
  expect(page.total).toBe(3);expect(page.data.map(v=>v.title)).toEqual(['Book 2','Book 3']);expect(page.nextOffset).toBe(2);
  expect((await q.knowledgeRecordPage(actor.workspaceId,database.id,{q:'quantum',filters:[{propertyId:ids.Pages,operator:'gte',value:2}],sort:ids.Pages,direction:'asc',limit:2,offset:2})).data.map(v=>v.title)).toEqual(['Book 4']);
  expect((await q.knowledgeRecordPage(actor.workspaceId,database.id,{filters:[{propertyId:ids.Read,operator:'eq',value:false}]})).total).toBe(5);
  for(const filter of [{propertyId:ids.Topics,operator:'contains',value:'Science'},{propertyId:ids.Topics,operator:'eq',value:['Science']},{propertyId:ids.Date,operator:'lte',value:'2026-09-23'}]) expect((await q.knowledgeRecordPage(actor.workspaceId,database.id,{filters:[filter]})).total).toBe(5);
  await expect(q.knowledgeRecordPage(actor.workspaceId,database.id,{filters:[{propertyId:ids.Pages,operator:'eq',value:'2'}]})).rejects.toMatchObject({code:'VALIDATION_FAILED'});
  const stored=await getDb().select().from(knowledgeValues).where(eq(knowledgeValues.recordId,page.data[0]!.id));
  expect(stored.find(v=>v.propertyId===ids.Pages)?.numberValue).toBe(2);expect(stored.find(v=>v.propertyId===ids.Read)?.booleanValue).toBe(false);
});
it('rolls back invalid writes and protects property identities, choices and deletion',async()=>{
  const {actor,database,ids}=await fixture();
  for(const value of ['wrong',true,[]]) await expect(k.createKnowledgeRecord(actor,database.id,{title:'Invalid',values:{[ids.Pages!]:value}})).rejects.toMatchObject({code:'VALIDATION_FAILED'});
  expect((await q.knowledgeRecordPage(actor.workspaceId,database.id,{})).total).toBe(0);
  await k.createKnowledgeRecord(actor,database.id,{title:'Kept',values:{[ids.Status!]:'Next'}});
  await expect(k.deleteKnowledgeProperty(actor,database.id,ids.Status!,1)).rejects.toMatchObject({code:'VALIDATION_FAILED'});
  await expect(k.deleteKnowledgeProperty(actor,database.id,ids.Title!,1)).rejects.toMatchObject({code:'VALIDATION_FAILED'});
  await expect(k.saveKnowledgeProperty(actor,database.id,ids.Status!,{version:1,property:{name:'State',type:'SELECT',config:{options:['Done']}}})).rejects.toMatchObject({code:'VALIDATION_FAILED'});
  await expect(k.saveKnowledgeProperty(actor,database.id,ids.Pages!,{version:1,property:{name:'Pages',type:'TEXT'}})).rejects.toMatchObject({code:'VALIDATION_FAILED'});
  const updated=await k.saveKnowledgeProperty(actor,database.id,ids.Pages!,{version:1,property:{name:'Length',type:'NUMBER',hidden:true}});
  expect(updated.properties.find(p=>p.id===ids.Pages)).toMatchObject({name:'Length',hidden:true});
  const ordered=await k.reorderKnowledgeProperties(actor,database.id,updated.version,updated.properties.map(p=>p.id).reverse());
  expect(ordered.properties[0]!.id).toBe(ids.Files);
});
it('rejects cross-workspace reads, values, links and direct foreign keys',async()=>{
  const a=await fixture(),b=await fixture();
  const record=await k.createKnowledgeRecord(a.actor,a.database.id,{title:'Private'});
  const other=await k.createKnowledgeRecord(b.actor,b.database.id,{title:'Other'});
  await expect(q.knowledgeRecordDetail(b.actor.workspaceId,record.id)).rejects.toMatchObject({code:'NOT_FOUND'});
  await expect(k.createKnowledgeRecord(a.actor,b.database.id,{title:'Wrong'})).rejects.toMatchObject({code:'NOT_FOUND'});
  await expect(k.updateKnowledgeRecord(a.actor,record.id,{version:1,title:'Wrong',values:{[b.ids.Pages!]:1}})).rejects.toMatchObject({code:'VALIDATION_FAILED'});
  await expect(r.linkKnowledgeRelation(a.actor,'record',record.id,{version:1,kind:'record',targetId:other.id,linked:true})).rejects.toMatchObject({code:'NOT_FOUND'});
  await expect(getDb().insert(knowledgeRecords).values({id:randomUUID(),workspaceId:a.actor.workspaceId,databaseId:b.database.id,title:'Wrong'})).rejects.toThrow();
  await expect(getDb().insert(knowledgeRelations).values({id:randomUUID(),workspaceId:a.actor.workspaceId,recordId:record.id,databaseId:a.database.id,kind:'record',targetId:other.id,targetRecordId:other.id})).rejects.toThrow();
});
it('detects concurrent edits, restores records, duplicates values, and keeps content out of audit',async()=>{
  const {actor,database,ids}=await fixture();const record=await k.createKnowledgeRecord(actor,database.id,{title:'Secret title',values:{[ids.Pages!]:0}});
  const writes=await Promise.allSettled(['A','B'].map(title=>k.updateKnowledgeRecord(actor,record.id,{version:1,title,content:'private content',values:{[ids.Pages!]:3}})));
  expect(writes.filter(w=>w.status==='fulfilled')).toHaveLength(1);
  expect(writes.find(w=>w.status==='rejected')).toMatchObject({reason:{code:'RESOURCE_VERSION_CONFLICT'}});
  const copy=await k.duplicateKnowledgeRecord(actor,record.id,2);expect((await q.knowledgeRecordDetail(actor.workspaceId,copy.id)).values[ids.Pages!]).toBe(3);
  const deleted=await k.setKnowledgeRecordDeleted(actor,record.id,2,true);expect((await q.knowledgeRecordPage(actor.workspaceId,database.id,{})).total).toBe(1);
  await k.setKnowledgeRecordDeleted(actor,record.id,deleted.version,false);expect((await q.knowledgeRecordPage(actor.workspaceId,database.id,{})).total).toBe(2);
  const audit=await getDb().select().from(auditLogs).where(eq(auditLogs.targetId,record.id));expect(JSON.stringify(audit)).not.toContain('private content');
  expect((await getDb().select().from(syncChanges).where(eq(syncChanges.entityId,record.id))).length).toBeGreaterThan(2);
});
it('links notes and records to existing tasks/goals with versioned backlinks',async()=>{
  const {actor,database}=await fixture();const record=await k.createKnowledgeRecord(actor,database.id,{title:'Reference'});
  const task=await createTask(actor,{workspaceId:actor.workspaceId,title:'Read',priority:'NONE',tagIds:[]});
  const goal=await createGoal(actor,{workspaceId:actor.workspaceId,title:'Learn',priority:'NONE'});
  const linked=await r.linkKnowledgeRelation(actor,'record',record.id,{version:1,kind:'task',targetId:task.id,linked:true});
  expect((await r.knowledgeBacklinks(actor.workspaceId,'task',task.id)).data[0]!.title).toBe('Reference');
  expect((await r.linkKnowledgeRelation(actor,'record',record.id,{version:linked.version,kind:'task',targetId:task.id,linked:true})).version).toBe(linked.version);
  const copy=await k.duplicateKnowledgeRecord(actor,record.id,linked.version);
  expect((await q.knowledgeRecordDetail(actor.workspaceId,copy.id)).relations.data[0]!.targetId).toBe(task.id);
  const note=await k.createKnowledgeNote(actor,{title:'Study note',content:'**Lesson**',recordId:record.id});
  await r.linkKnowledgeRelation(actor,'note',note.id,{version:1,kind:'goal',targetId:goal.id,linked:true});
  expect((await q.knowledgeRecordDetail(actor.workspaceId,record.id)).notes.data).toHaveLength(1);
  expect((await q.knowledgeNoteDetail(actor.workspaceId,note.id)).relations.data[0]!.target.label).toBe('Learn');
  await r.linkKnowledgeRelation(actor,'record',record.id,{version:linked.version,kind:'task',targetId:task.id,linked:false});
  expect((await r.knowledgeBacklinks(actor.workspaceId,'task',task.id)).data).toHaveLength(1);
});
it('supports standalone notes, owned tags, content search, deletion and restoration',async()=>{
  const a=await fixture(),b=await fixture();const tagId=randomUUID(),otherTag=randomUUID();
  await getDb().insert(tags).values([{id:tagId,workspaceId:a.actor.workspaceId,name:'Research'},{id:otherTag,workspaceId:b.actor.workspaceId,name:'Private'}]);
  await expect(k.createKnowledgeNote(a.actor,{title:'Wrong tag',tagIds:[otherTag]})).rejects.toMatchObject({code:'VALIDATION_FAILED'});
  const note=await k.createKnowledgeNote(a.actor,{title:'Standalone',content:'Searchable phrase',tagIds:[tagId]});
  expect((await q.listKnowledgeNotes(a.actor.workspaceId,{q:'Searchable'})).data).toHaveLength(1);
  expect((await q.knowledgeNoteDetail(a.actor.workspaceId,note.id)).tags).toEqual([{id:tagId,name:'Research'}]);
  const updated=await k.updateKnowledgeNote(a.actor,note.id,{version:1,title:'Updated',content:'New content',tagIds:[]});
  await expect(k.updateKnowledgeNote(a.actor,note.id,{version:1,title:'Stale',content:''})).rejects.toMatchObject({code:'RESOURCE_VERSION_CONFLICT'});
  const deleted=await k.setKnowledgeNoteDeleted(a.actor,note.id,updated.version,true);
  expect((await q.listKnowledgeNotes(a.actor.workspaceId,{})).data).toHaveLength(0);
  expect((await q.listKnowledgeNotes(a.actor.workspaceId,{includeDeleted:true})).data).toHaveLength(1);
  await k.setKnowledgeNoteDeleted(a.actor,note.id,deleted.version,false);
  expect((await q.knowledgeNoteDetail(a.actor.workspaceId,note.id)).note.content).toBe('New content');
});
it('honors related-database configuration and database archives without changing records',async()=>{
  const {actor,database,ids}=await fixture();const other=await k.createKnowledgeDatabase(actor,{name:'Target database'});
  const target=await k.createKnowledgeRecord(actor,other.id,{title:'Target'}),source=await k.createKnowledgeRecord(actor,database.id,{title:'Source'});
  const settings=await k.saveKnowledgeProperty(actor,database.id,ids.Related!,{version:1,property:{name:'Related',type:'RELATION',config:{relationKind:'record',relationDatabaseId:other.id}}});
  await expect(r.linkKnowledgeRelation(actor,'record',source.id,{version:1,propertyId:ids.Related,kind:'record',targetId:source.id,linked:true})).rejects.toMatchObject({code:'VALIDATION_FAILED'});
  await r.linkKnowledgeRelation(actor,'record',source.id,{version:1,propertyId:ids.Related,kind:'record',targetId:target.id,linked:true});
  await expect(k.saveKnowledgeProperty(actor,database.id,ids.Related!,{version:settings.version,property:{name:'Related',type:'RELATION',config:{relationKind:'task'}}})).rejects.toMatchObject({code:'VALIDATION_FAILED'});
  const archived=await k.updateKnowledgeDatabase(actor,database.id,{version:settings.version,archived:true,favorite:true});
  expect((await q.listKnowledgeDatabases(actor.workspaceId,{})).data.map(d=>d.id)).not.toContain(database.id);
  expect((await q.listKnowledgeDatabases(actor.workspaceId,{favorite:true,includeDeleted:true})).data.map(d=>d.id)).toEqual([database.id]);
  await expect(k.createKnowledgeRecord(actor,database.id,{title:'Blocked'})).rejects.toMatchObject({code:'VALIDATION_FAILED'});
  await k.updateKnowledgeDatabase(actor,database.id,{version:archived.version,archived:false});
  expect((await q.knowledgeRecordDetail(actor.workspaceId,source.id)).relations.data).toHaveLength(1);
  await expect(getDb().insert(knowledgeRelations).values({id:randomUUID(),workspaceId:actor.workspaceId,recordId:source.id,databaseId:database.id,propertyId:ids.Pages,kind:'record',targetId:target.id,targetRecordId:target.id})).rejects.toThrow();
});
it('copies templates independently and exports/purges the complete knowledge graph',async()=>{
  const {actor}=await fixture();
  const a=await k.createKnowledgeDatabase(actor,{name:'Books one',templateId:'books'}),b=await k.createKnowledgeDatabase(actor,{name:'Books two',templateId:'books'});
  expect(a.properties.map(p=>p.id).some(id=>b.properties.some(p=>p.id===id))).toBe(false);
  const record=await k.createKnowledgeRecord(actor,a.id,{title:'=formula',content:'Saved body'});
  const note=await k.createKnowledgeNote(actor,{title:'Note',databaseId:a.id});
  await r.linkKnowledgeRelation(actor,'note',note.id,{version:1,kind:'record',targetId:record.id,linked:true});
  expect((await q.exportKnowledgePage(actor.workspaceId,a.id,{},'csv')).content).toContain("'=formula");
  const exported=await buildExport(actor.userId);expect(exported.knowledgeRecords).toHaveLength(1);expect(exported.knowledgeRelations).toHaveLength(1);expect(exported.knowledgeNotes).toHaveLength(1);
  const old=new Date('2000-01-01');await getDb().update(users).set({deletionRequestedAt:old}).where(eq(users.id,actor.userId));
  expect(await purgeAccount(getDb(),actor.userId,new Date())).toBe(true);
  expect(await getDb().select().from(knowledgeRecords).where(eq(knowledgeRecords.workspaceId,actor.workspaceId))).toHaveLength(0);
});
