'use client';
import { usePersonalization } from '@/components/PersonalizationContext';
import { useEffect,useState,type ReactNode } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { api } from '@/lib/api';
import type { InsightsReport } from '@/server/services/insights';
import type { InsightsQuery } from '@nextdoo/contracts';

const number=(v:number|null|undefined)=>v==null?'Not available':new Intl.NumberFormat(undefined,{maximumFractionDigits:2}).format(v);
const percent=(v:number|null)=>v===null?'Not available':`${number(v*100)}%`;
function Metrics({values}:{values:[string,ReactNode][]}){return <dl className="insights-kpis">{values.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>;}
function Table({caption,head,rows}:{caption:string;head:string[];rows:ReactNode[][]}){return <div className="insights-table" tabIndex={0} role="region" aria-label={caption}><table><caption>{caption}</caption><thead><tr>{head.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table>{!rows.length&&<p>No data in this period.</p>}</div>;}
const objectLink=(kind:string,id:string)=>kind==='task'?`/tasks/${id}`:kind==='goal'||kind==='milestone'?`/goals/${id}`:kind==='record'?`/knowledge/records/${id}`:`/knowledge/notes/${id}`;

export function InsightsView({report=false}:{report?:boolean}){
  const search=useSearchParams();
  const {preferences}=usePersonalization();
  const [period,setPeriod]=useState<InsightsQuery['period']>((['day','week','month','quarter','year','custom'].includes(search.get('period')??'')?search.get('period'):preferences.insightsPeriod) as InsightsQuery['period']);
  const [date,setDate]=useState(search.get('date')??''),[from,setFrom]=useState(search.get('from')??''),[to,setTo]=useState(search.get('to')??''),[compare,setCompare]=useState(search.get('compare')==='true');
  const [data,setData]=useState<InsightsReport|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0),[exporting,setExporting]=useState(false),[exportError,setExportError]=useState('');
  const params=new URLSearchParams({period,compare:String(compare)});if(period==='custom'){params.set('from',from);params.set('to',to);}else if(date)params.set('date',date);
  const query=params.toString(),ready=period!=='custom'||!!(from&&to);
  useEffect(()=>{const controller=new AbortController();setData(null);setError('');setExportError('');if(ready)void api<InsightsReport>(`/insights?${query}`,{signal:controller.signal}).then(d=>{if(!controller.signal.aborted)setData(d);}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Could not load Insights.');});return ()=>controller.abort();},[query,ready,revision]);
  async function download(format:'csv'|'json'){
    setExporting(true);setExportError('');try{const result=await api<{content:string;filename:string;type:string}>(`/insights/export?${query}&format=${format}`);const url=URL.createObjectURL(new Blob([result.content],{type:result.type})),a=document.createElement('a');a.href=url;a.download=result.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setExportError(e instanceof Error?e.message:'Export failed.');}finally{setExporting(false);}
  }
  return <div className="insights-view">
    <div className="page-head"><div><h1>{report?'Insights report':'Insights'}</h1><p className="subtitle">Your work, progress, and what comes next.</p></div><Link className="insights-controls" href={`${report?'/insights':'/insights/reports'}?${query}`}>{report?'Back to Insights':'Open report'}</Link></div>
    <form className="card insights-controls insights-filters" onSubmit={e=>{e.preventDefault();setRevision(v=>v+1);}}>
      <label>Period<select aria-label="Period" value={period} onChange={e=>setPeriod(e.target.value as InsightsQuery['period'])}><option value="day">Today / Daily</option><option value="week">This week / Weekly</option><option value="month">This month / Monthly</option><option value="quarter">This quarter / Quarterly</option><option value="year">This year / Yearly</option><option value="custom">Custom date range</option></select></label>
      {period==='custom'?<><label>From<input aria-label="From" type="date" value={from} onChange={e=>setFrom(e.target.value)} required /></label><label>Through<input aria-label="Through" type="date" value={to} onChange={e=>setTo(e.target.value)} required /></label></>:<label>Date within period<input type="date" value={date} onChange={e=>setDate(e.target.value)} /><small>Leave blank for the current period.</small></label>}
      <label className="insights-check"><input type="checkbox" checked={compare} onChange={e=>setCompare(e.target.checked)} />Compare previous period</label><button type="submit">Refresh</button>
    </form>
    {!ready&&<p role="status">Choose both dates to load a custom report (up to 366 days).</p>}
    {error&&<p role="alert">{error}</p>}{ready&&!data&&!error&&<p role="status">Loading Insights…</p>}
    {data&&<>
      <p className="insights-period">{data.window.from} – {data.window.to} · {data.window.timeZone}</p><p className="muted">Snapshot: {new Date(data.generatedAt).toLocaleString()}. Activity uses the selected dates. Current status and upcoming deadlines are as of this snapshot.</p>
      <div className="row insights-controls"><button disabled={exporting} onClick={()=>void download('csv')}>Download CSV</button><button disabled={exporting} onClick={()=>void download('json')}>Download JSON</button>{report&&<button onClick={()=>window.print()}>Print report</button>}</div>{exportError&&<p role="alert">{exportError}</p>}
      {!data.tasks.created&&!data.tasks.completed&&!data.tasks.planned&&!data.goals.items.length&&!data.trackers.count&&!data.calendar.events&&!data.knowledge.databases&&!data.knowledge.notesCreated&&!data.knowledge.recordsCreated&&<p className="card">No activity to summarize yet. Create a task, goal, tracker, note, or calendar event to get started.</p>}
      <section className="card" aria-labelledby="insights-tasks"><h2 id="insights-tasks">Tasks & focus</h2><Metrics values={[
        ['Tasks completed',data.tasks.completed],['Tasks created',data.tasks.created],['Tasks due in period',data.tasks.planned],['Completed due tasks',data.tasks.completedPlanned],['Incomplete due tasks',data.tasks.incomplete],['Overdue due tasks',data.tasks.overdue],['Current overdue tasks',data.tasks.currentOverdue],['Completion rate',percent(data.tasks.completionRate)],['Recorded focus minutes',number(data.tasks.focusMinutes)],
      ]} /><p className="muted">Completion rate: currently completed tasks ÷ tasks due in this period. Incomplete means active. Focus uses saved timer minutes, including manual adjustments, on the session’s start date. Archived tasks remain in the due cohort; analytics exclusions apply.</p>
      <div className="insights-bars" role="img" aria-label={`Daily task completions for ${data.window.days} days. Exact values in the Task daily trend table.`}>{data.tasks.trend.map(d=><span key={d.day} title={`${d.day}: ${d.completed}`} style={{height:`${Math.max(2,100*d.completed/Math.max(1,...data.tasks.trend.map(v=>v.completed)))}%`}} />)}</div>
      <details open={report}><summary>Task daily trend and breakdowns</summary><Table caption="Task daily trend" head={['Date','Created','Completed','Due','Completed due','Focus minutes']} rows={data.tasks.trend.map(d=>[d.day,d.created,d.completed,d.planned,d.done,number(d.focusMinutes)])} />{(['byPriority','byStatus','byProject'] as const).map((key,i)=><Table key={key} caption={['Due tasks by priority','Due tasks by status','Due tasks by list / project (top 20)'][i]!} head={['Group','Tasks']} rows={data.tasks[key].map(v=>[v.title,v.count])} />)}</details></section>
      <section className="card" aria-labelledby="insights-goals"><h2 id="insights-goals">Goals & milestones</h2><Metrics values={[
        ['Active goals now',data.goals.active],['Goals completed in period',data.goals.completed],['Milestones completed in period',data.goals.completedMilestones],['Remaining milestones now',data.goals.remainingMilestones],['Overdue goals now',data.goals.overdue],['Overdue milestones now',data.goals.overdueMilestones],['Linked tasks completed now',`${data.goals.completedLinkedTasks} / ${data.goals.linkedTasks}`],
      ]} /><p className="muted">Progress is the current Goal Center calculation, including linked tasks and empty milestones. Historical progress percentages are not stored.</p>
      {data.goals.items.map(g=><div className="insights-goal" key={g.id}><Link href={`/goals/${g.id}`}>{g.title}</Link><span>{g.progress.percent===null?'No measurable units':`${g.progress.percent}% · ${g.progress.completed} / ${g.progress.total} units`}</span>{g.progress.percent!==null&&<progress max={100} value={g.progress.percent} aria-label={`${g.title} progress`} />}</div>)}{!data.goals.items.length&&<p>No goals yet.</p>}{data.goals.hasMore&&<Link href="/goals">First 50 shown. View all goals.</Link>}
      <details open={report}><summary>Goal completion trend</summary><Table caption="Goals completed by date" head={['Date','Completed']} rows={data.goals.trend.map(d=>[d.day,d.completed])} /></details></section>
      <section className="card" aria-labelledby="insights-trackers"><h2 id="insights-trackers">Tracker consistency</h2><Metrics values={[
        ['Trackers',data.trackers.count],['Tracked days',data.trackers.trackedDays],['Eligible tracker-days',data.trackers.calendarDays],['Unscored days',data.trackers.unscoredDays],...(data.preferences.scoresEnabled?[['Total stars',number(data.trackers.totalStars)],['Average stars',number(data.trackers.averageStars)],['Relative stars',number(data.trackers.relativeStars)]] as [string,ReactNode][]:[]),
      ]} /><p className="muted">Each tracker keeps its own time zone and start date. Average = total stars ÷ eligible calendar days; relative = total stars ÷ recorded days. Missing dates are not invented entries. Scores use the saved Tracker results. Streaks count consecutive recorded dates inside this range; the ending streak must reach the last eligible date.</p>
      {!data.preferences.scoresEnabled&&<p>Numeric scores are hidden in Wellbeing settings.</p>}
      <Table caption="Tracker comparison" head={['Tracker','Time zone','Recorded / eligible days',...(data.preferences.scoresEnabled?['Total stars','Average','Relative']:[]),...(data.preferences.streaksEnabled?['Longest streak','Ending streak']:[])]} rows={data.trackers.items.map(t=>[<Link key={t.id} href={`/trackers/${t.id}`}>{t.name}</Link>,t.timeZone,`${t.trackedDays} / ${t.calendarDays}`,...(data.preferences.scoresEnabled?[number(t.totalStars),number(t.averageStars),number(t.relativeStars)]:[]),...(data.preferences.streaksEnabled?[t.streaks?.longest??0,t.streaks?.current??0]:[])])} />
      <Table caption="Tracker status distribution" head={['Status','Days']} rows={Object.entries(data.trackers.statusDistribution)} />
      <details open={report}><summary>Daily, weekly, and monthly tracker trends</summary>{(['trend','weekly','monthly'] as const).map((key,i)=><Table key={key} caption={['Daily tracker trend','Weekly tracker trend (Monday start)','Monthly tracker trend'][i]!} head={['Period','Tracked days',...(data.preferences.scoresEnabled?['Total stars']:[])]} rows={data.trackers[key].map(d=>['day' in d?d.day:d.period,d.trackedDays,...(data.preferences.scoresEnabled?[number(d.totalStars)]:[])])} />)}</details></section>
      <section className="card" aria-labelledby="insights-calendar"><h2 id="insights-calendar">Calendar workload</h2><Metrics values={[
        ['Scheduled events',data.calendar.events],['All-day events',data.calendar.allDayEvents],['Scheduled minutes',number(data.calendar.scheduledMinutes)],['Visible task deadlines',data.calendar.taskDeadlines],
      ]} /><p className="muted">Visible native, imported, and connected calendars. Timed events are clipped to the period; overlapping events add separately. All-day events have no invented duration. Scheduled time is separate from recorded focus time. Task deadlines follow task-layer visibility.</p><details open={report}><summary>Daily calendar workload</summary><Table caption="Calendar workload by date" head={['Date','Events','All day','Scheduled minutes']} rows={data.calendar.days.map(d=>[d.day,d.events,d.allDayEvents,number(d.scheduledMinutes)])} /></details></section>
      <section className="card" aria-labelledby="insights-knowledge"><h2 id="insights-knowledge">Knowledge & Data</h2><Metrics values={[
        ['Databases now',data.knowledge.databases],['Records created',data.knowledge.recordsCreated],['Notes created',data.knowledge.notesCreated],
      ]} /><Link href="/knowledge">Open Knowledge & Data</Link></section>
      <section className="card" aria-labelledby="insights-comparison"><h2 id="insights-comparison">Previous period comparison</h2>{data.comparisonReason&&<p>{data.comparisonReason} <Link href="/settings">Wellbeing settings</Link></p>}{data.comparison&&<><p>Change from {data.comparison.window.from} – {data.comparison.window.to} ({data.window.days} local dates).</p><Metrics values={[
        ['Completed tasks change',number(data.comparison.tasksCompleted)],['Completion rate change (percentage points)',number(data.comparison.completionRate===null?null:data.comparison.completionRate*100)],['Focus minutes change',number(data.comparison.focusMinutes)],['Tracked days change',number(data.comparison.trackedDays)],...(data.preferences.scoresEnabled?[['Tracker stars change',number(data.comparison.trackerStars)]] as [string,ReactNode][]:[]),
      ]} /></>}</section>
      {(['recent','upcoming'] as const).map(key=><section key={key} className="card" aria-label={key==='recent'?'Recent activity':'Upcoming deadlines'}><h2>{key==='recent'?'Recent activity':'Upcoming deadlines'}</h2><p className="muted">{key==='recent'?'Latest 20 task/goal completions and note/record creations in this period.':'Next 20 active task, goal, and milestone deadlines as of this snapshot.'}</p>{!data.activity[key].length?<p>{key==='recent'?'No recent activity in this period.':'No upcoming deadlines.'}</p>:<ul>{data.activity[key].map((a,i)=><li key={`${a.kind}:${a.id}:${i}`}><Link href={objectLink(a.kind,a.id)}>{a.title}</Link> · {a.kind} · {new Date(a.at).toLocaleString(undefined,{timeZone:data.window.timeZone})}</li>)}</ul>}</section>)}
      {report&&<p>Use Print report for your browser’s print or Save as PDF options. Downloaded reports are snapshots and are not stored on the server.</p>}
    </>}
  </div>;
}
